- jaxrs-api/src/main/java/javax/ws/rs/ext/RuntimeDelegate.java
- jaxrs-api/src/test/java/javax/ws/rs/ext/RuntimeDelegateTest.java
This implements a fix for issue #581: Problem with RuntimeDelegate.getInstance().
> Fix issue 581: Problem with RuntimeDelegate.getInstance()

- jaxrs-api/src/main/java/javax/ws/rs/core/CacheControl.java
- jaxrs-api/src/main/java/javax/ws/rs/core/Cookie.java
- jaxrs-api/src/main/java/javax/ws/rs/core/EntityTag.java
- jaxrs-api/src/main/java/javax/ws/rs/core/NewCookie.java
- jaxrs-api/src/test/java/javax/ws/rs/core/EntityTagTest.java
> Deprecate use of HEADER_DELEGATE #607

- jaxrs-api/src/main/java/javax/ws/rs/client/ClientResponseFilter.java
**As this is just the absolutely minimal change -adding a single parenthesis- I will apply a shortened review period of just five days.**
Signed-off-by: Markus KARG <markus@headcrashing.eu>
> Fixed Javadoc typo: Missing closing parenthesis

- CONTRIBUTING.md
- NOTICE.md
These are required files for release process.
> New CONTRIBUTING and NOTICE files.

- Jenkinsfile
Fixes nightly builds, so they actually run _automatically_ now (not just manually).
**Review Period: As this is a pure project configuration PR, I will merge this PR _as soon as_ two reviewers approved it.**
> Automatically trigger nightly builds

- .travis.yml
- jaxrs-api/pom.xml
Support for building JAX-RS API on JDK 11
Closes #636
> Builds on JDK11

- examples/pom.xml
- jaxrs-api/pom.xml
Changing Maven Coordinates according PMC's request.
**The review period for this change is only five days, as this change is needed rather immediately by the Jakarta build team.**
> Changed groupId and artifactId. Fixes #663 (EE4J_8)

- jaxrs-api/pom.xml
Signed-off-by: Dmitry Kornilov <dmitry.kornilov@oracle.com>
> spec-version plugin configuration fixed

- .gitignore
Signed-off-by: arjantijms <arjan.tijms@gmail.com>
> Added gitignore entries for Eclipse, NetBeans and VS Code

- examples/pom.xml
- jaxrs-api/pom.xml
I assume we shall stage Version 2.1.3 on OSSRH next (not the current 2.1.3-SNAPSHOT). :-)
**As projects are waiting downstreams, I propose a fast-track review period of just one day. If you are not happy with that short period, please immediately -1 this in the PR's comments!**
> Version 2.1.3

- jaxrs-api/pom.xml
Add build-helper-maven-plugin to put NOTICE.md and LICENSE.md to META-INF
Set Bundle-SymbolicName = jakarta.ws.rs-api
Signed-off-by: Jan Supol <jan.supol@oracle.com>
> Prepare 2.1.4 release

- examples/pom.xml
- jaxrs-api/pom.xml
**This PR will be fast-tracked as it does not change any source code at all but solely fixes legal files of the bundle. The minimum review period is one day according to the [new fast-track rules](https://github.com/eclipse-ee4j/jaxrs-api/wiki/Committer-Conventions#voting-rules) we agreed upon recently.**
*All committers please check the staged 2.1.5-SNAPSHOT build whether the release should be done (+1) or should be withhold (-1). In particular please double-check the OSGi manifest and all legal issues.. Thanks.*
> Release 2.1.5

- jaxrs-api/src/main/java/javax/ws/rs/core/Request.java
Signed-off-by: Anthony Vanelverdinghe <anthonyv.be@outlook.com>
Fixes #747
> Update Request.evaluatePreconditions() to match RFC 7232

- jaxrs-api/pom.xml
- jaxrs-api/src/main/javadoc/overview.html
- jaxrs-api/src/main/javadoc/resources/EFSL.html
Inclusion and reference to the EFSL as described in release process.
Requesting **fast track**.
Signed-off-by: Santiago Pericas-Geertsen <santiago.pericasgeertsen@oracle.com>
> Include reference to license from javadocs

- examples/pom.xml
- jaxrs-api/pom.xml
- jaxrs-spec/pom.xml
Will be merged when getting the necessary approvals.
Signed-off-by: Santiago Pericas-Geertsen <santiago.pericasgeertsen@oracle.com>
> Release 2.1.6

- jaxrs-api/pom.xml
- jaxrs-api/src/main/java/javax/ws/rs/client/ClientBuilder.java
- jaxrs-spec/pom.xml
- jaxrs-spec/src/main/asciidoc/license-efsl.adoc
These changes were requested during the release process. Needs fast tracking.
> Changes requested for Jakarta EE release

- jaxrs-spec/src/main/asciidoc/chapters/filters_and_interceptors/_filters.adoc
- jaxrs-spec/src/main/asciidoc/chapters/filters_and_interceptors/_introduction_filters.adoc
#804 Complete the missing information about extension points for filters and interceptors.
> [#804] Spec: Fix text for Filters and Interceptors: Introduction and Filter

- jaxrs-spec/src/main/asciidoc/chapters/applications/_publication.adoc
- jaxrs-spec/src/main/asciidoc/chapters/client_api/_client_api.adoc
- jaxrs-spec/src/main/asciidoc/chapters/client_api/_resource_access.adoc
- jaxrs-spec/src/main/asciidoc/chapters/client_api/_typed-entities.adoc
- jaxrs-spec/src/main/asciidoc/chapters/filters_and_interceptors/_introduction_filters.adoc
- jaxrs-spec/src/main/asciidoc/chapters/filters_and_interceptors/_priorities.adoc
- jaxrs-spec/src/main/asciidoc/chapters/providers/_entity_providers.adoc
- jaxrs-spec/src/main/asciidoc/chapters/providers/_lifecycle_and_environment.adoc
- jaxrs-spec/src/main/asciidoc/chapters/runtimedelegate/_rdconfig.adoc
- jaxrs-spec/src/main/asciidoc/chapters/sse/_sse_environment.adoc
- jaxrs-spec/src/main/asciidoc/chapters/validation/_validation_and_error_reporting.adoc
Update Chapter 2.3 (Publication sub-chapter) by changing all references to javax to jakarta.
[my first attempt to contribute to the Jakarta Project. want to see if I have gotten the process and steps right. Pardon me for I am wrong]
> [#804] Spec: Update Chapter 2.3 (Publication sub-chapter)

- examples/pom.xml
- jaxrs-api/pom.xml
- jaxrs-spec/pom.xml
Updating the pom.xml files to reflect 3.0.0-M1 for a milestone 1 release.  Please review this quickly as I would like to publish the milestone release by the end of the month - this should be considered a fast-track PR.  Thanks!
> Release 3.0.0-M1

- CONTRIBUTING.md
#869 Fast track
Add section on Eclipse Development Process
Signed-off-by: arjantijms <arjan.tijms@gmail.com>
> #869 Eclipse Development Process

- examples/pom.xml
- jaxrs-api/pom.xml
There are new releases of EJB and CDI and the JAXB implementation we use in our tests. This PR updates our dependencies.
> Updated Jakarta dependencies

- jaxrs-api/src/main/java/jakarta/ws/rs/sse/SseBroadcaster.java
Issue: https://github.com/eclipse-ee4j/jaxrs-api/issues/745
> [745] Clarify more about SseBrodcaster.onClose() behavior

- examples/pom.xml
- jaxrs-api/pom.xml
- jaxrs-spec/pom.xml
Preparation for Release 3.0.0. Fast track.
> Updated files for Release 3.0.0

- jaxrs-api/pom.xml
- jaxrs-api/src/main/javadoc/resources/EFSL.html
- jaxrs-spec/src/main/asciidoc/chapters/license/_license-efsl.adoc
Closing #896 
Undoing recent EFSL changes (originally requested by @kwsutter) as requested by @kwsutter.
> [#896] Undo EFSL changes

- jaxrs-spec/pom.xml
Removed draft status. Fast Track.
> Removed draft status

- jaxrs-api/src/main/java/jakarta/ws/rs/core/HttpHeaders.java
> Adding Expect header of HTTP/1.1 spec

- examples/pom.xml
Collection of useful steps towards examples v3.1
> Preparing examples v3.1

- .travis.yml
Testing with OpenJDK 17 on Travis CI/CD
> Travis openjdk17

- examples/src/main/java/jaxrs/examples/bootstrap/ClientAuthenticationJavaSeBootstrapExample.java
- examples/src/main/java/jaxrs/examples/bootstrap/HttpsJavaSeBootstrapExample.java
- examples/src/main/java/jaxrs/examples/link/LinkExamples.java
- examples/src/main/java/jaxrs/examples/sse/ItemStoreResource.java
Fixed the javadoc issues in examples:
> Fix Examples JavaDoc

- .github/workflows/maven-package.yml
Mostly to test Actions. JDK 11 only. Requesting fast track.
> Initial setup for GitHub Actions

- jaxrs-api/src/main/java/jakarta/ws/rs/sse/SseEventSource.java
This PR is my proposal to fix [issue 992](https://github.com/eclipse-ee4j/jaxrs-api/issues/992).
Let me know what you think.
Thanks
> Clarify behavior when SseEvent source onEvent throws and exception

- examples/src/main/java/jaxrs/examples/bootstrap/BasicJavaSeBootstrapExample.java
- examples/src/main/java/jaxrs/examples/bootstrap/ClientAuthenticationJavaSeBootstrapExample.java
- examples/src/main/java/jaxrs/examples/bootstrap/ExplicitJavaSeBootstrapExample.java
- examples/src/main/java/jaxrs/examples/bootstrap/ExternalConfigJavaSeBootstrapExample.java
- examples/src/main/java/jaxrs/examples/bootstrap/HttpsJavaSeBootstrapExample.java
- examples/src/main/java/jaxrs/examples/bootstrap/NativeJavaSeBootstrapExample.java
- examples/src/main/java/jaxrs/examples/bootstrap/PropertyProviderJavaSeBootstrapExample.java
- examples/src/main/java/jaxrs/examples/bootstrap/TlsJavaSeBootstrapExample.java
- jaxrs-api/src/main/java/jakarta/ws/rs/SeBootstrap.java
- jaxrs-api/src/main/java/jakarta/ws/rs/core/EntityPart.java
- jaxrs-api/src/main/java/jakarta/ws/rs/ext/RuntimeDelegate.java
- jaxrs-api/src/test/java/jakarta/ws/rs/SeBootstrapTest.java
Provides boilerplate simplification for SeBootstrap API:
1. New methods for default config
2. New methods for class instances
3. New method for shutdown hooks
4. New methods to obtain baseUri's
5. Removal of redundant public/final/etc as flagged by modern IDE's
6. Update to examples
See issue #1009 for an example.
> Provides boilerplate simplification for SeBootstrap API

- jaxrs-api/src/main/java/jakarta/ws/rs/core/EntityPart.java
> Use GenericEntity for List<EntityPart> entity in EntityPart javadoc.

- jaxrs-tck/src/main/java/jakarta/ws/rs/tck/common/provider/StringBeanRuntimeDelegate.java
> Update TCK RuntimeDelegate to comply with API new method

- jaxrs-api/src/main/java/jakarta/ws/rs/SeBootstrap.java
As discussed with @mkarg and @chkal this is a first fix for #978 
**Requesting a fast track review since this is not a change to the public API.**
> #978 Fix some unused imports to make checkstyle happy

- Jenkinsfile
- examples/pom.xml
- jaxrs-api/pom.xml
- jaxrs-spec/README.md
- jaxrs-spec/pom.xml
- jaxrs-spec/src/main/asciidoc/chapters/introduction/_status.adoc
- jaxrs-spec/src/main/asciidoc/chapters/license/_license-efsl.adoc
- jaxrs-tck/pom.xml
- jersey-tck/pom.xml
- pom.xml
In addition to the version changes, this PR includes changes for our Jenkins pipeline necessary after the recent pom changes.
> Updates in preparation for 3.1.0 release

- jaxrs-api/src/main/java/jakarta/ws/rs/core/NewCookie.java
> Fix NPE for NewCookie#equals when simesite is null

- jaxrs-tck/src/main/java/jakarta/ws/rs/tck/api/rs/core/responseclient/JAXRSClientIT.java
> Update tck tests regarding new Response.Statuses

- jaxrs-tck/src/main/java/jakarta/ws/rs/tck/api/rs/core/linkjaxbadapter/JAXRSClientIT.java
- jaxrs-tck/src/main/java/jakarta/ws/rs/tck/api/rs/core/newcookie/JAXRSClientIT.java
- jaxrs-tck/src/main/java/jakarta/ws/rs/tck/api/rs/ext/interceptor/reader/interceptorcontext/JAXRSClientIT.java
- jaxrs-tck/src/main/java/jakarta/ws/rs/tck/api/rs/ext/interceptor/reader/readerinterceptorcontext/JAXRSClientIT.java
- jaxrs-tck/src/main/java/jakarta/ws/rs/tck/ee/rs/core/securitycontext/basic/JAXRSBasicClientIT.java
- jaxrs-tck/src/main/java/jakarta/ws/rs/tck/ee/rs/ext/providers/JAXRSProvidersClientIT.java
- jaxrs-tck/src/main/java/jakarta/ws/rs/tck/jaxrs21/ee/client/executor/async/JAXRSClientIT.java
- jaxrs-tck/src/main/java/jakarta/ws/rs/tck/jaxrs21/ee/sse/ssebroadcaster/JAXRSClientIT.java
- jaxrs-tck/src/main/java/jakarta/ws/rs/tck/jaxrs21/ee/sse/sseeventsource/JAXRSClientIT.java
- jaxrs-tck/src/main/java/jakarta/ws/rs/tck/spec/resource/responsemediatype/JAXRSClientIT.java
The excluded tests are marked with annotation  `@Disabled` to skip the test.
> TCK Migration : Mark the excluded list of tests as per ts.jtx in jaxrs tck from jakartaee-tck

- jaxrs-tck/src/main/java/jakarta/ws/rs/tck/ee/rs/container/requestcontext/security/JAXRSClientIT.java
- jaxrs-tck/src/main/java/jakarta/ws/rs/tck/ee/rs/core/securitycontext/basic/JAXRSBasicClientIT.java
- jersey-tck/pom.xml
- jersey-tck/src/main/java/org/glassfish/jersey/core/tck/JerseyApplicationArchiveProcessor.java
- jersey-tck/src/main/java/org/glassfish/jersey/core/tck/JerseyLoadableExtension.java
- jersey-tck/src/main/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
- jersey-tck/src/main/resources/jaxrs_ee_core_securitycontext_basic_web.war.sun-web.xml
- jersey-tck/src/main/resources/jaxrs_ee_rs_container_requestcontext_security_web.war.sun-web.xml
> Using Arquillian SPI for extending wars by vendor specific descriptors.

- jaxrs-api/src/main/java/jakarta/ws/rs/client/Entity.java
- jaxrs-api/src/main/java/jakarta/ws/rs/core/CacheControl.java
- jaxrs-api/src/main/java/jakarta/ws/rs/core/Cookie.java
- jaxrs-api/src/main/java/jakarta/ws/rs/core/GenericEntity.java
- jaxrs-api/src/main/java/jakarta/ws/rs/core/Link.java
- jaxrs-api/src/main/java/jakarta/ws/rs/core/NewCookie.java
- jaxrs-api/src/main/java/jakarta/ws/rs/core/Variant.java
It makes not much sense to maintain custom code if there is a simple JRE replacement. :-)
> Replaced custom code by JRE standards

- jersey-tck/pom.xml
Fixes https://github.com/eclipse-ee4j/jaxrs-api/issues/1079 .
Requesting **fast-track review** for this one as it changes neither the api nor the spec.
> cleanup javajoe/j2ee users and stop glassfish domain 

- jaxrs-tck/pom.xml
- jaxrs-tck/src/main/java/jakarta/ws/rs/tck/jaxrs31/spec/extensions/JAXRSClientIT.java
Regressions after PR #1082. Fixed artifactId, imports and reformatted pom for consistency. Should fix pipeline regressions too.
Request fast track.
> Fixed some regressions after package renaming

- jersey-tck/pom.xml
> Split executions of server tests & se tests

- jaxrs-api/pom.xml
> Updated dependencies for EE10.

- jaxrs-tck-docs/TCK-Exclude-List.txt
- jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/jaxrs21/ee/sse/ssebroadcaster/JAXRSClientIT.java
> fast-track: 1162 sse broadcast test

- jaxrs-api/src/main/java/jakarta/ws/rs/BeanParam.java
- jaxrs-api/src/main/java/jakarta/ws/rs/container/ResourceContext.java
- jaxrs-api/src/main/java/jakarta/ws/rs/core/Application.java
- jaxrs-api/src/main/java/jakarta/ws/rs/core/Configurable.java
- jaxrs-api/src/main/java/jakarta/ws/rs/core/Configuration.java
- jaxrs-api/src/main/java/jakarta/ws/rs/core/HttpHeaders.java
- jaxrs-api/src/main/java/jakarta/ws/rs/core/SecurityContext.java
- jaxrs-api/src/main/java/jakarta/ws/rs/core/UriInfo.java
- jaxrs-api/src/main/java/jakarta/ws/rs/ext/ContextResolver.java
- jaxrs-api/src/main/java/jakarta/ws/rs/ext/Providers.java
- jaxrs-api/src/main/java/jakarta/ws/rs/sse/SseEventSink.java
> Fixed some problems with Entity and Context in comments

- jaxrs-spec/src/main/asciidoc/chapters/appendix/_annotation_table.adoc
- jaxrs-spec/src/main/asciidoc/chapters/appendix/_change-log.adoc
- jaxrs-spec/src/main/asciidoc/chapters/appendix/_changes-since-3.1-release.adoc
- jaxrs-spec/src/main/asciidoc/chapters/asynchronous_processing/_async_ejbs.adoc
- jaxrs-spec/src/main/asciidoc/chapters/context/_contexttypes.adoc
- jaxrs-spec/src/main/asciidoc/chapters/environment/_javaee.adoc
- jaxrs-spec/src/main/asciidoc/chapters/environment/_servlet_container.adoc
- jaxrs-spec/src/main/asciidoc/chapters/introduction/_status.adoc
- jaxrs-spec/src/main/asciidoc/chapters/providers/_lifecycle_and_environment.adoc
- jaxrs-spec/src/main/asciidoc/chapters/resources/_resource-classes.adoc
- jaxrs-spec/src/main/asciidoc/chapters/resources/_resource_field.adoc
- jaxrs-spec/src/main/asciidoc/chapters/sse/_sse_broadcasting.adoc
- jaxrs-spec/src/main/asciidoc/chapters/sse/_sse_server_api.adoc
- jaxrs-spec/src/main/asciidoc/chapters/validation/_validation_and_error_reporting.adoc
First pass at changes needed to Jakarta Rest-4.0 specification.
> M1 spec changes1

- jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/ee/rs/container/responsecontext/ResponseFilter.java
Relates to https://github.com/jakartaee/rest/issues/1199
In master
> TCK Challenge: ee.jakarta.tck.ws.rs.ee.rs.container.responsecontext.JAXRSClientIT#setStatusInfoTest and #setStatusTest

- .github/workflows/maven-package.yml
- examples/pom.xml
- jaxrs-api/pom.xml
- jaxrs-spec/pom.xml
- jaxrs-spec/src/main/asciidoc/chapters/introduction/_status.adoc
- jaxrs-tck-docs/tckbundle.sh
- jaxrs-tck-docs/userguide/pom.xml
- jaxrs-tck/pom.xml
- jersey-tck/pom.xml
- pom.xml
Also update CI to run on this branch.
> Bump the release-3.2 branch version to 3.2.0-SNAPSHOT

- examples/src/main/java/jaxrs/examples/multipart/MultipartClient.java
> Fix multipart example with addition of GenericEntity

- jaxrs-tck/src/main/resources/ee/jakarta/tck/ws/rs/signaturetest/jakarta.ws.rs.sig_4.0.0
Note this will need an addition after #1236 and #1143 are merged.
> fast-track: Update the signature test file for the removal of Jakarta XML Binding types

- jaxrs-tck/docs/assertions/JAXRSJavadocAssertions_4.0.0.html
- jaxrs-tck/docs/assertions/JAXRSJavadocAssertions_4.0.0.xml
Generated API/JavaDoc Assertions XML for JAXRS 4.0 using https://github.com/eclipse-ee4j/jakartaee-tck-tools/blob/master/tools/scripts/assert-gen.sh.
cc @jansupol @spericas @jim-krueger
> Javadoc Assertions for JAXRS 4.0 in TCK

- jaxrs-api/src/main/java/jakarta/ws/rs/core/MediaType.java
New JSON types. Originally contributed by ribandcoder in PR #1143 but pipeline was blocked. Issue #1141.
**Fast track** because original PR was approved and ready to merge.
> New JSON types in MediaType

- jaxrs-spec/src/main/asciidoc/chapters/appendix/_changes-since-3.1-release.adoc
- jaxrs-spec/src/main/asciidoc/chapters/applications/_publication.adoc
- jaxrs-tck/docs/assertions/JAXRSSpecAssertions_3.1.0.html
- jaxrs-tck/docs/assertions/JAXRSSpecAssertions_3.1.0.xml
> fast-track: Clarify the JavaSE support in Jakarta Rest Specification

- jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/ee/rs/container/requestcontext/JAXRSClientIT.java
Fixes #1278.
See #1278 and #1279 for details.
> Fix TCK failure in getHeaders test

- jaxrs-api/src/main/java/jakarta/ws/rs/core/GenericType.java
> Avoid using old synchronized java.util.Stack

- jaxrs-api/src/main/java/jakarta/ws/rs/core/MediaType.java
Adds `application/yaml` MediaType
closes #1272
> feat: application/yaml MediaType
