jakartaee/rest

etc/config/checkstyle.xml, jaxrs-api/pom.xml
This pull request is a first step to address #587 and a subset of #588. It contains just the update of the Checkstyle Maven plugin. 
Beside updating the plugin version, this pull request also:
* Ignores `module-info.java`, because Checkstyle completely fails while parsing it.
* Removes the `RedundantThrows` rule, which has been removed from Checkstyle (see checkstyle/checkstyle#473)
Further adjustments of the Checkstyle configuration will be provided in separate pull requests.
=> Updated Checkstyle (#587)

jaxrs-api/src/main/java/javax/ws/rs/FormParam.java
The pull request fixes the broken API docs of `@FormParam` as described in #589. It simply moves the second part of the sentence one line up and removes the redundant `</li>` element.
PS: I'm not sure if this is something for the `2.1.1-SNAPSHOT`. But as we also need it in `2.2-SNAPSHOT` we could cherry-pick it to the `2.1.1-SNAPSHOT` branch if required.
=> Fixed broken HTML in FormParam API docs (#589)

jaxrs-api/src/main/java/javax/ws/rs/core/AbstractMultivaluedMap.java, jaxrs-api/src/test/java/javax/ws/rs/core/MultivaluedHashMapTest.java
- Added Serializable interface to AbstractMultivaluedMap
- Renamed MultivaluedMapTest -> MultivaluedHashMapTest to match tested class
This should fix #527
=> Fix Issue 527: MultivaluedHashMap is not deserializable

jaxrs-api/src/main/java/javax/ws/rs/client/Client.java
Looking at issue #472 I found that Response, SseBroadcaster, SseEventSink, SseEventSource already implement AutoCloseable.
The only class that has a "void close()" method and that does not implement AutoCloseable is Client.
This PR adds the AutoCloseable interface to Client.
=> Classes should implement java.lang.AutoCloseable where applicable (#472)

etc/config/checkstyle.xml
Currently Checkstyle reports 2516 (!) violations in the source code. The number increased dramatically after updating Checkstyle as part of #595.
A majority of the violations is caused by the `WhitespaceAround` rule, which is currently configured to enforce whitespaces around `<` and `>`. Therefore, this rule is violated for all generic declarations like `List<String>`.
This pull requests updates the Checkstyle configuration to not check for whitespaces around `<` and `>` anymore, which reduces the total number of violations to 674.
=> Adjusted Checkstyle's WhitespaceAround rule for generics (#587)

jaxrs-api/pom.xml
Since adding a new dependency is probably a change that should be discussed on its own I have created this PR instead of adding the dependency as part of #593.
I think by now mock testing is a standard in using testing, so we should use mock testing. Especially since we are only creating an API, mocking the implementation part will help in a lot of cases.
=> Add mockito test dependency (2.16)

.travis.yml, README.md
The Eclipse Webmaster team has already enabled Travis for our repository.
https://bugs.eclipse.org/bugs/show_bug.cgi?id=533020
This pull request contains a first simple `.travis.yml` file. It will build both the API and the example project with JDK8 and JDK9. I think that's a good start. 
Unfortunately JDK10 isn't available on Travis by default, but there are ways to install it manually during the build. I'll provide a separate pull request for an enhanced setup with more JDK versions in the next days.
=> First version of .travis.yml

jaxrs-api/src/main/java/javax/ws/rs/container/AsyncResponse.java, jaxrs-api/src/main/java/javax/ws/rs/core/Link.java
This pull requests will fix two issues in the API docs which Checkstyle found in the code:
* The API docs of `AsyncResponse` contain a `</p>` without a matching `<p>` element. Browsers will most likely either ignore this or create a matching `<p>` automatically, which will add additional margin.
* The API docs of `Link` contain a `<emph>` element, which doesn't exist in HTML. I replaced this with `<em>` which is most likely the element that the original author had in mind.
=> Fixed invalid HTML in API docs

jaxrs-api/pom.xml, jaxrs-api/src/main/java/javax/ws/rs/core/EntityTag.java, jaxrs-api/src/test/java/javax/ws/rs/core/EntityTagTest.java
This PR fixes issue #426 and simplifies equals/hashcode in EntityTag.
As correctly stated in the ticket the call to super.equals() can never return true, since the super is a simple instance comparison.
I have also used the Objects.equals()/hash() methods to simplify the code.
I am not particulary happy with the test since it has the side effect of initializing the EntityType.HEADER_DELEGATE to null. But I do not see any way around this as long as the HEADER_DELEGATE field is is initialized on class initialization. Perhaps this field should be "inlined" in the toString() method (but I am not sure on the performance implications of this)
The test rule could later be extended to add more functionality (if needed in other tests)
=> Cleanup EntityTag.equals() / hashcode() (#426)

jaxrs-api/src/main/java/javax/ws/rs/core/Configuration.java
This pull requests clarifies which classes are returned from `Configuration.getClasses()`. Especially it states that the resulting set will include root resource classes and that the result of this method will return a complete runtime view which includes auto-detected components.
Please see #565 for the corresponding discussion.
As this pull request isn't an API change and has been discussed before, the review period will be one week. Feel free to comment if you prefer a two week period.
=> Clarify which components are returned from Configuration#getClasses()

jaxrs-api/src/main/java/javax/ws/rs/core/Feature.java
This pull requests adds a clarification to the API docs of the `Feature` provider interface which describes that auto-discovery via `@Provider` is supported for server side features.
Please see #583 for the corresponding discussion.
As this pull request isn't a API change and has been discussed before, the review period will be one week.
=> Clarify that Feature supports auto-discovery via @Provider (#583)

jaxrs-api/.gitignore, jaxrs-api/pom.xml
With this PR I'd like to propose some minor improvements to the pom.xml file:
- Getting rid of `groupId` lines wherevery possible, following a Maven best-practice: Using CoC for default group IDs.
- Correcting the `organization` element, which now says "Eclipse Foundation" not "Oracle" anymore.
- Bumping versions of Maven plugins to catch up with months to years of bug fixes.
=> Minor improvements to pom.xml

jaxrs-api/pom.xml
Fixes the following problem when building JDK9 using maven-surefire-plugin:2.21.0+:
```
[ERROR] testSerializationOfJaxbLink(javax.ws.rs.core.JaxbLinkTest)  Time elapsed: 0.296 s  <<< ERROR!
java.lang.reflect.InaccessibleObjectException: Unable to make void javax.ws.rs.core.Link$JaxbLink.setParams(java.util.Map) accessible: module java.ws.rs does not "opens javax.ws.rs.core" to module java.xml.bind
at java.ws.rs/javax.ws.rs.core.JaxbLinkTest.testSerializationOfJaxbLink(JaxbLinkTest.java:47)
```
=> Fixed: Building on JDK9 using maven-surefire-plugin:2.21.0

jaxrs-api/pom.xml
Currently used maven-bundle-plugin 3.5.0 seems to work fine with module-info, so apparently there is no more need for separate packaging types on JDK 8- vs. JDK 9+.
Closing #627
=> Static packaging type 'bundle' instead of property

Jenkinsfile, examples/pom.xml, jaxrs-api/pom.xml
This PR sets up the minimal infrastructure needed for publishing nightly builds of branch 'master'.
The job is performed using the Eclipse Foundation's own infrastructure (i. e. without neither Travis CI nor Maven Central).
The EF's Jenkins service (Jenkins with multi-branch pipeline, see https://ci.eclipse.org/jaxrs/job/Nightly%20Build) uses a Jenkinsfile, which in turn instructs Maven to publish on the EF's Nexus service. The latter is publicly readable, so nightly builds can be accessed by the broad public easily, either by manual download, or by adding the EF's repo as an additional Maven dependency repo.
Jenkins: https://ci.eclipse.org/jaxrs/
Nexus: https://repo.eclipse.org/content/repositories/jax-rs-api/
_This PR solely provides nightly builds, but intentionally does not provide a …
=> Publishing nightly builds of master branch (#634)

.travis.yml, Jenkinsfile, README.md, examples/pom.xml, jaxrs-api/pom.xml
**Enabling nightly builds for EE4J_8 / 2.1.1-SNAPSHOT _in preparation of_ a "JAX-RS 2.1 (Jakarta EE branded)" release (currently prepared by @spericas in #638)**
This PR sets up the minimal infrastructure needed for publishing nightly builds of branch 'EE4J_8 / 2.1.1-SNAPSHOT' [plus enables Travis CI for _immediate_ PR-validation].
The nightly build job is performed using the Eclipse Foundation's own infrastructure (i. e. without neither Travis CI nor Maven Central) [but Travis CI is _enabled_ by this PR for _immediate_ PR-validation].
The EF's Jenkins service (Jenkins with multi-branch pipeline, see https://ci.eclipse.org/jaxrs/job/Nightly%20Build) uses a Jenkinsfile, which in turn instructs Maven to publish on the EF's Nexus service. The latter is publicly readable, so nightly builds …
=> Publishing nightly builds of branches EE4J_8 / 2.1.1-SNAPSHOT

.travis.yml
Although we will most likely use the Jenkins instance provided by the Eclipse Foundation in the future, we could update our Travis configuration to run the build about all relevant JDKs. Travis recently introduced support for more JDK versions, so I modified the config accordingly.
Please note that while testing the new configuration, I discovered that the build currently does NOT work with the EA versions of JDK11. I'll create a separate issue for that.
=> Run Travis build against more JDK versions

.travis.yml
Backporting this into the nightly builds of 2.1.1 / EE4J_8
**As we already merged this into master (i. e. 2.2), I will apply a one-day review period only to not slow us down unnecessarily. If you do not want this backport, please immediate reject the PR now!**
=> Run Travis build against more JDK versions (in 2.1.1 / EE4J_8)

jaxrs-api/src/main/java/javax/ws/rs/core/UriBuilder.java
Allowing application programmers to use `UriBuilder` created *from scratch*, i. e. prividing *all* parts separately *without* having a valid URI/template to start with.
There are situations where it just comes handy to construct URIs from scratch using a builder pattern, i. e. not using valid URI as a starting point. One example is when one wants to format a pretty-printed URI string from the distinct parts provided to the new `JAXRS.Configuration` builder for informational use (like the examples do) or inside of an implementation (like Jersey does). The Javadocs of `UriBuilder` already says `...for building URIs from their components` but this never was true: Until now one couldn't build *from components* but always had to build from a *valid* URI/template and then *modify* components. …
=> public UriBuilder.newInstance()

jaxrs-api/src/main/java/javax/ws/rs/client/ClientRequestFilter.java, jaxrs-api/src/main/java/javax/ws/rs/client/ClientResponseFilter.java
According to JAX-RS 2.2 specification, `@Provider` MUST be set on Filters and Interceptors (this includes ClientFilter) _only_ for discovery.
Signed-off-by: Markus KARG <markus@headcrashing.eu>
=> ClientFilter need @Provider only for discovery

jaxrs-api/pom.xml
**This PR implements the needed changes ontop of branch `EE4J_8` to release JAX-RS 2.1.1 using OSSRH.**
When performing `mvn deploy -P release` the following happens:
* Signs artifacts using GPG.
* Publishes to OSSRH (either snapshot repo or staging repo for publication on The Central Repository).
Usage for publishing a release on The Central Repository:
* Step 1: *Manually* perform a release (i. e. create a PR containing the version change and let the committers review it). *I abstain from the Maven Release plugin as it brings us no measurable benefit in this particular project, does not fit in the EF's typical "committers have to vote" policy, and it won't work due to our branch protection.*
* Step 2: Start the "[Publish Release](https://ci.eclipse.org/jaxrs/job/Publish%20Release/)" job …
=> Release Process: GPG Signing & OSSRH Nexus Staging

examples/pom.xml, examples/src/main/java/jaxrs/examples/bootstrap/BasicJavaSeBootstrapExample.java, examples/src/main/java/jaxrs/examples/bootstrap/ClientAuthenticationJavaSeBootstrapExample.java, examples/src/main/java/jaxrs/examples/bootstrap/ExplicitJavaSeBootstrapExample.java, examples/src/main/java/jaxrs/examples/bootstrap/ExternalConfigJavaSeBootstrapExample.java, examples/src/main/java/jaxrs/examples/bootstrap/HelloWorld.java, examples/src/main/java/jaxrs/examples/bootstrap/HttpsJavaSeBootstrapExample.java, examples/src/main/java/jaxrs/examples/bootstrap/NativeJavaSeBootstrapExample.java, examples/src/main/java/jaxrs/examples/bootstrap/PropertyProviderJavaSeBootstrapExample.java, examples/src/main/java/jaxrs/examples/bootstrap/TlsJavaSeBootstrapExample.java, examples/src/main/java/jaxrs/examples/bootstrap/package-info.java, jaxrs-api/src/main/java/javax/ws/rs/JAXRS.java, jaxrs-api/src/main/java/javax/ws/rs/ext/RuntimeDelegate.java, jaxrs-api/src/test/java/javax/ws/rs/JAXRSTest.java, jaxrs-api/src/test/java/javax/ws/rs/core/RuntimeDelegateStub.java
This PR implements a vendor-neutral way to bootstrap JAX-RS applications in pure Java SE environments (i. e. making the application self-contained, without being powered by an application server product). It just provides a common API for starting up the application and runtime, but does not make any contstraints about supported features or technology.
Signed-off-by: Markus KARG <markus@headcrashing.eu>
=> Java SE Bootstrapping API

examples/pom.xml, jaxrs-api/pom.xml, jaxrs-api/src/main/java/javax/ws/rs/FormParam.java, jaxrs-api/src/main/java/javax/ws/rs/client/ClientRequestFilter.java, jaxrs-api/src/main/java/javax/ws/rs/client/ClientResponseFilter.java, jaxrs-api/src/main/java/javax/ws/rs/container/AsyncResponse.java, jaxrs-api/src/main/java/javax/ws/rs/core/Feature.java, jaxrs-api/src/main/java/javax/ws/rs/core/Link.java
This PR includes a number of fixes cherry picked from the master branch that are simply clarifications to the 2.1 Javadoc. This should be the last PR in preparation for the 2.1.1 release. Oracle will provide TCK results for the final bits using the RI (Jersey) --TCKs also include signature tests that will confirm no changes were to the API in 2.1.1 compared to 2.1.
=> Preparation for Release 2.1.1

jaxrs-api/pom.xml
This PR provides minimum information requested by OSSRH.
I hope that the automated OSSRH POM check allows generic `<developers>` section. This is not detailed anywhere.
=> POM additions requested by OSSRH

jaxrs-api/src/main/java/javax/ws/rs/JAXRS.java
New configuration option `JAXRS.Configuration.FREE_PORT=0` issues scanning for a free port when starting a server using the Java SE Bootstrap API.
=> Free IP port scan using JAXRS.Configuration.FREE_PORT=0

CONTRIBUTING.md, NOTICE.md, jaxrs-api/pom.xml
Changes taken from `EE4J_8` needed to publish `master` at a later time to OSSRH.
=> Lessons learned from publishing 2.1.1 to OSSRH

jaxrs-api/src/main/java/module-info.java
This is required for implementors with JPMS to implement the
ClientBuilder, RuntimeDelegate, and SseEventSource.Builder.
This resolves issue #661.
Due to JPMS unit testing issues described in Pull Request #658 [comment](https://github.com/eclipse-ee4j/jaxrs-api/pull/658#issuecomment-422459421), I don't have any unit tests for this.  However, I was able to test this using a basic Java application on Java 10 with a module-info.java like this:
```
module andymc.jaxrs.stubs {
requires java.ws.rs;
provides javax.ws.rs.client.ClientBuilder
with io.andymc.jaxrs.stubs.ClientBuilderStub;
provides javax.ws.rs.ext.RuntimeDelegate
with io.andymc.jaxrs.stubs.RuntimeDelegateStub;
provides javax.ws.rs.sse.SseEventSource.Builder
with io.andymc.jaxrs.stubs.SseEventSourceBuilderStub;
} 
```
and a main …
=> Add uses clauses to module-info.java

.travis.yml, examples/pom.xml, jaxrs-api/.gitignore, jaxrs-api/pom.xml, jaxrs-api/src/main/java/module-info.java
This is a proposal to cherry-pick *more* "non-essential" bug fixes from `master` to `EE4J_8` in the form another service release: JAX-RS 2.1.2.
*There had been several voices saying that these bug fixes are wanted in 2.1.2, so it is **up to the committers** to decide whether we actually cherry-pick them or not.*
While technically there are several commits contained, effectively what they produce simply spoken is:
* Will build fine on JDK11 (several commits needed for that, as Maven plugins are failing in EE4J_8)
* JPMS module declaration corrected
* Examples reference Jakarta EE instead of Java EE (existing bug in current EE4J_8 branch)
*As this is only a service release, and as the actual API is not touched we can just push to OSSRH without the need of another review by EMO / PMC. Having …
=> JAX-RS 2.1.2 (Bug fixes ontop JAX-RS 2.1.1)

examples/pom.xml, jaxrs-api/pom.xml
This PR is a *rollup* of all commits between 2.1.1 and 2.1.2 (`EE4J_8`) into 2.2-SNAPSHOT (`master`).
* Changes Maven Coordinates from `javax` to `jakarta` as requested by PMC.
* *(All other commits of `EE4J-8` existed in `master` already.)*
=> 2.1.2 Rollup

.travis.yml
Due to Oracle's recent changes in their support policy, Travis CI does not suppot oraclejdk10 anymore.
It fails the build with the following message:
```
oraclejdk10 is deprecated. See https://www.oracle.com/technetwork/java/javase/eol-135779.html for more details. Consider using openjdk10 instead.
```
This PR follows that given advice and simply removes oraclejdk10, as openjdk10 is already supported.
=> Travis CI does not support oraclejdk10 anymore

jaxrs-api/pom.xml
As @jansupol pointed out in #681, we don't need `Automatic-Module-Name` anymore, because we now have a real `module-info.java`. Therefore, it should be safe to remove the manifest entry.
As this PR only doesn't change the JAX-RS API, I would like to apply the rule for the reduced review period of one week.
Please note that we should also backport this PR to the `EE4J_8` branch.
=> Removed Automatic-Module-Name from manifest

.travis.yml, jaxrs-api/pom.xml
I had a deeper look at the OSGi manifest issues described in #681. It looks like the wrong version numbers were created because the `final` profile wasn't active during the release. Unfortunately activating this profile currently fails the build with:
```
[INFO] --- spec-version-maven-plugin:1.5:check-module (default) @ jakarta.ws.rs-api ---
[ jakarta.ws.rs:jakarta.ws.rs-api:2.1.2 ]
{ groupIdPrefix=jakarta. spec-version=2.2 apiPackage=javax.ws.rs API final spec-impl-version=2.1.2 }
- WARNING: spec-impl-version (2.1.2) must start with JCP spec-version number (2.2)
```
The root cause for this seems to be that the Maven properties `last.final.spec.version` and `next.final.spec.version` aren't set correctly. As the `EE4J_8` branch is a maintenance branch for JAX-RS 2.1, the properties need to …
=> Fixed spec-version properties and Travis config for 2.1 releases

.travis.yml
See discussion in:
https://github.com/eclipse-ee4j/jaxrs-api/pull/692
JDK 11 support is not a requirement for this branch. We shall continue to test with JDK 11 in our master branch. 
I propose to fast track this PR.
Signed-off-by: Santiago Pericas-Geertsen <Santiago.PericasGeertsen@oracle.com>
=> Removed Travis JDK 11 support in EE4J_8 branch

jaxrs-api/pom.xml
Changing dependencies from javax to jakarta as requested by @m0mus in https://github.com/eclipse-ee4j/jaxrs-api/issues/690.
**No API is changed. To help minimize the delay of GlassFish release, I hereby request a shortened review period of only five days.**
*This PR will not build until JAF and JAXB have released to Maven Central, which is intended, to ensure that JAX-RS does not depend on pre-releases but always only depends upon publicly released components. To prevent the need of refreshing votes, it is advisory to wait with the voting until Travis CI approves the build.*
=> Dependencies migrated from javax to jakarta

jaxrs-api/pom.xml
This pull request is basically a proof of concept that shows how the build could look like if we replace the `spec-version-maven-plugin` with explicit configuration of the relevant manifest entries.
Please note that the PR removes some Maven properties which aren't required anymore. It also removes the concept of the `nonFinal` flag which was the root cause of the weird version numbers created.
Most of the manifest attributes are generated exactly the same way as before. The only noteworthy difference is the handling of the version related attributes:
* `Bundle-Version`
* This is the OSGi bundle version
* The previous value was `2.1` or `2.1.2` with the `final` profile and `2.1.99.b01` without it.
* The value is now the same as the Maven project version normalized to the OSGi format. For …
=> Replaced spec-version-maven-plugin with explicit configuration

jaxrs-api/src/main/java/javax/ws/rs/core/MediaType.java
The struct is immutable, reuse the result of hash code
This makes it more efficient to use MediaType as keys in hash maps, caches and other hash-based strucutres.
* single computation of hash code
* final fields
=> MediaType improvements

jaxrs-api/pom.xml
As JDK11+ explicitly requests a particular version of JAXB, it is more safe to exclude the version of JAXB implicitly contained by the JRE itself.
*Replaces https://github.com/eclipse-ee4j/jaxrs-api/pull/699*
**The review period ends after seven days already, as this is a replacement of #699, which already started seven days ago.**
=> Excluding JRE's implied JAXB implementation with JDK11+

jaxrs-api/pom.xml
This PR is a *rollup* of all commits between 2.1.2 and 2.1.3 (`EE4J_8`) into 2.2-SNAPSHOT (`master`).
* Changes Maven Coordinates of dependencies from `javax` to `jakarta` as requested by PMC.
* Fixes OSGi manifest as requested by team Jersey.
* *(All other commits of `EE4J-8` existed in `master` already.)*
**As these are no API changes, and as all these changes are already contained in `EE4J_8` I propose a reduced review period of just five days.**
=> 2.1.3 Rollup

examples/pom.xml, jaxrs-api/pom.xml
See https://github.com/eclipse-ee4j/jaxrs-api/issues/714.
**This PR will be fast-tracked as it does not change any source code at all but solely fixes the technical form of the bundle. The minimum review period is one day according to the [new fast-track rules](https://github.com/eclipse-ee4j/jaxrs-api/wiki/Committer-Conventions#voting-rules) we agreed upon recently.**
*All committers pleace check today's nightly build whether the release should be done (+1) or should be withhold (-1). In particular please double-check the OSGi manifest and all legal issues. I noticed that the snapshot contains the version number "2.1.3" in the OSGi declarations, so please OSGi experts do confirm that this will be correctly turn to "2.1.4" as soon as this is not a snapshot anymore. Thanks.*
=> Release 2.1.4

jaxrs-api/pom.xml
This PR is a *rollup* of all commits between 2.1.3 and 2.1.4 (`EE4J_8`) into 2.2-SNAPSHOT (`master`).
* Adding missing files in JAR demanded by EF.
* Fixes OSGi manifest as requested by downstream teams.
**As these are no API changes, and as all these changes are already contained in `EE4J_8` I propose a fast-track review period of just one day as per our [recently update committer rules](https://github.com/eclipse-ee4j/jaxrs-api/wiki/Committer-Conventions#minimum-length-of-review-period-before-merge--close-of-prs-and-closing-of-issues).**
**This PR is to be merged *before* the 2.1.5-rollup (#723)!**
=> 2.1.4 Rollup

jaxrs-api/pom.xml
This PR modifies the branch `EE4J_8` so it can be built using the new Eclipse Foundation CI Infrastructure (Jenkins).
See #721 and https://wiki.eclipse.org/EE4J_Build.
=> New Eclipse Foundation CI Infrastructure (Jenkins)

examples/pom.xml, jaxrs-api/pom.xml, jaxrs-api/src/main/java/javax/ws/rs/client/ClientBuilder.java
This PR is a *rollup* of all commits between 2.1.4 and 2.1.5 (`EE4J_8`) into 2.2-SNAPSHOT (`master`).
* Adding missing files in JAR demanded by EF.
* Minor fixes.
**As these are no API changes, and as all these changes are already contained in `EE4J_8` I propose a fast-track review period of just one day as per our [recently update committer rules](https://github.com/eclipse-ee4j/jaxrs-api/wiki/Committer-Conventions#minimum-length-of-review-period-before-merge--close-of-prs-and-closing-of-issues).**
**This PR is to be merged *after* the 2.1.4-rollup (#717)!**
**Ths PR is to be merged *after* fixing the current build probles (#724)!**
=> 2.1.5-Rollup

examples/pom.xml, examples/src/main/java/jaxrs/examples/sse/ItemStoreResource.java, jaxrs-api/pom.xml, jaxrs-api/src/main/java/javax/ws/rs/container/ContainerResponseContext.java, jaxrs-api/src/main/java/javax/ws/rs/core/Link.java, jaxrs-api/src/main/java/javax/ws/rs/core/MultivaluedHashMap.java, jaxrs-api/src/main/java/javax/ws/rs/core/Response.java, jaxrs-api/src/main/java/javax/ws/rs/core/UriInfo.java, jaxrs-api/src/main/java/javax/ws/rs/sse/SseEventSource.java
Latest JavaDoc does not allow `<tt>` anymore as it was deprecated with HTML 5, hence replacing it by `<code>` or `{@code}`.
=> Fixed JavaDocs: <tt> must either be <code> or {@code}

jaxrs-api/src/main/java/javax/ws/rs/core/MediaType.java, jaxrs-api/src/test/java/javax/ws/rs/core/MediaTypeTest.java
As described in https://github.com/eclipse-ee4j/jaxrs-api/issues/543, the `javax.ws.rs.core.MediaType#isCompatible` method is not behaving as expected when one of the media types to be compared has a wildcard type and explicit subtype, e.g. `*/json`. The referred media type is considered to be compatible with any type, even if the subtypes do not match (e.g. `*/json` will be considered compatible with `application/octet-stream`). As such, if an implementation of JAX-RS relies on `javax.ws.rs.core.MediaType#isCompatible` to determine if the media type of an incoming request is compatible with the accepted media types of a resource method, as per Section 3.5 of the specification (via Step 3a in Section 3.7.2), it might result in a surprising behaviour for the end-user.
This change aims to …
=> Improve MediaType compatibility check

Jenkinsfile
This is the same as #724 but this time we need it for `EE4J_8`.
=> Releasing using OpenJDK (latest) instead of 8uX.

Jenkinsfile
The EF's new Jenkins infrastructure needs a change in the Jenkinsfiles:
The external Maven configuration files have to be explicitly declared
now.
**This fix is for the `EE4J_8` branch. A similar for exists for the `master` branch (#738).**
=> Jenkinsfile explicitly refers to external config files [New Infrastructure] [EE4J_8]

Jenkinsfile, jaxrs-api/pom.xml
The EF's new Jenkins infrastructure needs a change in the Jenkinsfiles: The external Maven configuration files have to be explicitly declared now.
**This fix is for the `master` branch. A similar fix exists for the `EE4J_8` branch (#737).**
=> Jenkinsfile explicitly refers to external config files [New Infrastructure] [master]

jaxrs-api/src/main/java/javax/ws/rs/ext/MessageBodyWriter.java
Closing #730 by JavaDoc change: unambiguously forbid MBWs to close the stream.
=> JavaDocs: MBW#writeTo MUST NOT close the stream

jaxrs-api/src/main/java/javax/ws/rs/JAXRS.java, jaxrs-api/src/main/java/javax/ws/rs/client/ClientRequestContext.java, jaxrs-api/src/main/java/javax/ws/rs/container/ContainerRequestContext.java, jaxrs-api/src/main/java/javax/ws/rs/core/Configuration.java, jaxrs-api/src/main/java/javax/ws/rs/ext/InterceptorContext.java
In some circumstances it might be beneficial to have a new method `InterceptorContext#hasProperty(String name)` which simply returns `true` if a property name is known to the context. As of JAX-RS 2.1 it is possible to workaround this by `InterceptorContext#getProperty(String name) != null`, but this might imply a performance penalty in case the implementation needs *additionional time* to actually retrieve the value of the property. Some implementations might benefit from having this method, and some application programmers might like the brevity of this new method.
This PR implements this as a `default` interface method, so implementations can decide to either implement a performance improved variant, or simply stay with the default solution without breaking backwards compatibility.
=> New method #hasProperty

.travis.yml
Improves Travis CI performance by loading one big folder instead of running a lot of single dependency downloads (in my tests, performance was about doubled). :-)
Unfortunately EF has no similar solution at hand for Jenkins (at least right now off-the-box). :-(
=> Travis CI is caching local Maven Repository

jaxrs-api/src/main/java/javax/ws/rs/ext/MessageBodyReader.java, jaxrs-api/src/main/java/javax/ws/rs/ext/MessageBodyWriter.java
This pull request addresses #711 by clarifying, in which situations MBW/MBR pipelines are executed. There was already some discussions about the reasoning for this wording in #711, so please refer to these comments if you want to learn more about the details.
=> Clarify in which situations MBW/MBR pipelines are executed (#711)

jaxrs-api/pom.xml
Fixes #734 by using Maven Javadoc Plugin 3.1.0
**As these are no API changes, I propose a fast-track review period of just one day as per our [current committer rules](https://github.com/eclipse-ee4j/jaxrs-api/wiki/Committer-Conventions#minimum-length-of-review-period-before-merge--close-of-prs-and-closing-of-issues).**
=> Fix for #734 (Javadoc fails on JDK 11 and later)

.travis.yml
This PR prepares CI for building on JDK12.
It intentionally only adds OpenJDK but not OracleJDK anymore, due to several reasons:
* Oracle claims there is no difference between OracleJDK and OpenJDK anymore other than branding and support.
* Prevent frequent CI add-and-remove actions due to Oracle's recent support changes.
* Prepare a level playing field for all vendors. Otherwise we would have to add support of Azul and others who also provide repackaged OpenJDKs.
**As of today, this build will break as Travis CI does not support JDK12 already. This PR solely is solely *preparing* support, so we could merge it as soon as Travis CI is ready. Nevertheless, feel free to discuss and review already!**
=> CI on JDK12

.travis.yml, examples/src/main/java/jaxrs/examples/sse/ItemStoreResource.java, jaxrs-api/pom.xml, jaxrs-api/src/main/java/javax/ws/rs/container/ContainerResponseContext.java, jaxrs-api/src/main/java/javax/ws/rs/core/Link.java, jaxrs-api/src/main/java/javax/ws/rs/core/MultivaluedHashMap.java, jaxrs-api/src/main/java/javax/ws/rs/core/Response.java, jaxrs-api/src/main/java/javax/ws/rs/core/UriInfo.java, jaxrs-api/src/main/java/javax/ws/rs/sse/SseEventSource.java
To detect problems as soon as possible, Travis now generates JavaDocs and runs integration tests.
=> Travis generates JavaDoc and runs integration tests

jaxrs-api/src/main/java/javax/ws/rs/ext/Extension.java
This proposed feature standardizes an API for **JAX-RS Extensions**.
While JAX-RS components since ever could be *explicitly declared* to be loaded by `Application` classes, only *some* environments could auto-detect them *without* such explicit declaration of the application. In environments *not* supporting auto-detection this is not nice, because JAX-RS components might be provided on the classpath to be used with *any* application, i. e. *without* both, neither the application provider's knowledge or explicit grant, nor the runtime vendor's. Examples could be tracing and monitoring functionality, possibly from third parties (like cloud providers) *combining* JAX-RS *applications* with JAX-RS *runtimes*.
So JAX-RS Extensions provide a third origin of components on the classpath, …
=> JAX-RS Extensions

jaxrs-api/src/main/java/javax/ws/rs/client/ClientBuilder.java, jaxrs-api/src/main/java/javax/ws/rs/client/FactoryFinder.java, jaxrs-api/src/main/java/javax/ws/rs/ext/FactoryFinder.java, jaxrs-api/src/main/java/javax/ws/rs/ext/RuntimeDelegate.java, jaxrs-api/src/main/java/javax/ws/rs/sse/FactoryFinder.java, jaxrs-api/src/main/java/javax/ws/rs/sse/SseEventSource.java
This PR finishes the work started by PR #592: While #592 solved issue #581 in one location, this new PR solves the same issue on all remaining locations - it removes the dependency to Jersey.
Also this PR removes the fallback class name parameter completely, as it is unused now, as suggested by @andymc12.
=> [581] Remove Jersey as default implementation

jaxrs-api/src/main/java/javax/ws/rs/ext/ParamConverter.java
The `ParamConverter` API is mentioned only briefly in section 3.2 of the specification document like this:
> Valid parameter types for each of the above annotations are listed in the corresponding Javadoc, however in general (excluding `@Context` ) the following types are supported:
> 1. Types for which a `ParamConverter` is available via a registered `ParamConverterProvider`. See
Javadoc for these classes for more information.
> 2. [...]
Unfortunately JAX-RS implementations aren't handling all aspects of this API in the same way. RESTEasy for example completely ignores `ParamConverters` for all primitive types (see [RESTEASY-2222](https://issues.jboss.org/browse/RESTEASY-2222) for details). Although the spec isn't very explicit about which types are supported, I don't see any reason why …
=> Clarify that ParamConverters must be preferred and work with all types

.travis.yml, jaxrs-api/pom.xml, jaxrs-api/src/main/java/jakarta/ws/rs/client/package-info.java, jaxrs-api/src/main/java/jakarta/ws/rs/core/Configurable.java, jaxrs-api/src/main/java/jakarta/ws/rs/sse/SseEventSource.java, jaxrs-api/src/main/javadoc/overview.html
This PR provides all needed changes to also build on JDK 13:
- Travis CI uses Open JDK 13
- Mockito 3.1.0 needed as Mockito 2.x will not run anymore on JDK 13
- JavaDoc 13 implies new restrictions on the sequence of `<Hn>`
=> Additionally building on JDK 13

examples/src/main/java/jaxrs/examples/bootstrap/BasicJavaSeBootstrapExample.java, examples/src/main/java/jaxrs/examples/bootstrap/ClientAuthenticationJavaSeBootstrapExample.java, examples/src/main/java/jaxrs/examples/bootstrap/ExplicitJavaSeBootstrapExample.java, examples/src/main/java/jaxrs/examples/bootstrap/ExternalConfigJavaSeBootstrapExample.java, examples/src/main/java/jaxrs/examples/bootstrap/HttpsJavaSeBootstrapExample.java, examples/src/main/java/jaxrs/examples/bootstrap/NativeJavaSeBootstrapExample.java, examples/src/main/java/jaxrs/examples/bootstrap/PropertyProviderJavaSeBootstrapExample.java, examples/src/main/java/jaxrs/examples/bootstrap/TlsJavaSeBootstrapExample.java, examples/src/main/java/jaxrs/examples/bootstrap/package-info.java, jaxrs-api/src/main/java/jakarta/ws/rs/SeBootstrap.java, jaxrs-api/src/main/java/jakarta/ws/rs/ext/RuntimeDelegate.java, jaxrs-api/src/test/java/jakarta/ws/rs/SeBootstrapTest.java, jaxrs-api/src/test/java/jakarta/ws/rs/core/RuntimeDelegateStub.java
Renamed Java SE Bootstrap interface from `JAXRS` to `SeBootstrap` as proposed by @jansupol and objected by nobody (see discussion in #770).
Closes #770.
*According to our [Committer Conventions](https://github.com/eclipse-ee4j/jaxrs-api/wiki/Committer-Conventions) the review time for this PR is two full weeks.*
=> GH-770 Rename JAXRS interface

.travis.yml, jaxrs-spec/pom.xml
- Spec: Can also build spec on JDK 9 and later now
- Spec: Travis CI/CD builds spec
=> Spec: Technical Fixes

jaxrs-spec/assembly.xml, jaxrs-spec/pom.xml, jaxrs-spec/src/main/asciidoc/chapters/appendix/_bibliography.adoc
Replace any "http://" occurrence in an external link with "https://".
gh-804
=> [#804] Spec: Use “https://” instead of “http://” for any external link

jaxrs-spec/src/main/asciidoc/chapters/appendix/_bibliography.adoc
Modifying references to the JCP with corresponding Eclipse processes (excluding Activation and JAX-WS)
=> [#804] Modifying references to the JCP with corresponding Eclipse processes (excluding Activation and JAX-WS)

Jenkinsfile
Fixed: Nightly Build fails after after migration to ci.eclipse.org
Solution: Not using configuration files for Jenkins jobs
=> Migration of Jenkins files (Fixed Nightly Build)

examples/pom.xml, jaxrs-api/pom.xml, jaxrs-spec/pom.xml
According to our recently changed [roadmap](https://github.com/eclipse-ee4j/jaxrs-api/wiki/Roadmap) the `master` branch actually is not working towards release 2.2 but actually towards releasse 3.1 (in fact it skips release 3.0 as it already contains new features).
=> Renamed 2.2-SNAPSHOT -> 3.1-SNAPSHOT

jaxrs-api/src/main/java/jakarta/ws/rs/core/Response.java
=> [#554] Fix javadoc for Response.created()

NOTICE.md, jaxrs-api/pom.xml, jaxrs-api/src/main/java/jakarta/ws/rs/client/ClientBuilder.java, jaxrs-api/src/main/javadoc/overview.html, jaxrs-api/src/main/javadoc/resources/EFSL.html
This PR is a *rollup* of all commits between 2.1.5 and 2.1.6 (`2.1-Maintenance`, formerly `EE4J_8`) into `3.1-SNAPSHOT` (`master`).
**As these are no API changes, and as all these changes are already contained in `EE4J_8` I propose a fast-track review period of just one day as per our [committer rules](https://github.com/eclipse-ee4j/jaxrs-api/wiki/Committer-Conventions#minimum-length-of-review-period-before-merge--close-of-prs-and-closing-of-issues).**
=> 2.1.6-Rollup

jaxrs-api/pom.xml
Replacing license names in `pom.xml` by [SPDX indentifiers](https://spdx.org/licenses/) to allow *unambiguous and automatic* identification of the actual license.
Closes #816.
Replaces #817 
=> [#816] Update the license names in pom.xml to use proper SPDX identifier

_config.yml
The link "Documentation" in the navigation bar now opens the JAX-RS 2.1 specification (HTML on jakarta.ee page).
Demo: https://mkarg.github.io/jaxrs-api/?version=f2e4af012eea9a60e9cc4d34e645060961215ce2.
We should discuss *later* (*after* this pure bug fix) to replace the link by the Jakarta EE 9's variant of the spec (i. e. replace the boilerplate spec by the actual spec). For that. But this is out of scope for *this* PR.
=> [Spec] Fixed: Link to current spec

jaxrs-api/pom.xml
PMC member @dblevins announced that between January 2nd and 6th we have to migrate to the dedicated host `jakarta.oss.sonatype.org`:
>All,
>
>We've struggled with the 30 day expiration of oss.sonatype.org.  Sonatype has very generously agreed to dedicate an instance of Nexus Pro specifically to us and our Jakarta efforts that will give us a 60 day retention policy.
>
>Here's the information I have:
>
>- Thursday, January 2nd new instance available for testing at jakarta.oss.sonatype.org
>
>- Monday, January 6th cutover -- publishing to Central from oss.sonatype.org will cease to work
>
>- Users in the "Migrate" tab will be migrated.  Users in the "Hold" tab are welcome to opt-in (there will be another batch) 
>
>https://docs.google.com/spreadsheets/d/10eQJ46CyqcK8lco2z8dEN_9c29Wql_E_eSU8fe …
=> Migrated to https://jakarta.oss.sonatype.org

examples/src/main/java/jaxrs/examples/bootstrap/BasicJavaSeBootstrapExample.java, examples/src/main/java/jaxrs/examples/bootstrap/ClientAuthenticationJavaSeBootstrapExample.java, examples/src/main/java/jaxrs/examples/bootstrap/ExplicitJavaSeBootstrapExample.java, examples/src/main/java/jaxrs/examples/bootstrap/ExternalConfigJavaSeBootstrapExample.java, examples/src/main/java/jaxrs/examples/bootstrap/HelloWorld.java, examples/src/main/java/jaxrs/examples/bootstrap/HttpsJavaSeBootstrapExample.java, examples/src/main/java/jaxrs/examples/bootstrap/NativeJavaSeBootstrapExample.java, examples/src/main/java/jaxrs/examples/bootstrap/PropertyProviderJavaSeBootstrapExample.java, examples/src/main/java/jaxrs/examples/bootstrap/TlsJavaSeBootstrapExample.java, examples/src/main/java/jaxrs/examples/bootstrap/package-info.java, jaxrs-api/src/main/java/jakarta/ws/rs/SeBootstrap.java, jaxrs-api/src/main/java/jakarta/ws/rs/core/UriBuilder.java, jaxrs-api/src/test/java/jakarta/ws/rs/SeBootstrapTest.java
Corrected `@since 2.2` to `@since 3.1` for API changes, according to the platform team's request that Jakarta EE 9 shall have no API changes other than the package migration. So we will split JAX-RS 2.2 into JAX-RS 3.0 (without new features) and JAX-RS 3.1 (including new features). As a consequence, `@since` has to get corrected.
**As these are no API changes, and as all these changes are already contained in `EE4J_8` I propose a fast-track review period of just one day as per our [committer rules](https://github.com/eclipse-ee4j/jaxrs-api/wiki/Committer-Conventions#minimum-length-of-review-period-before-merge--close-of-prs-and-closing-of-issues).**
=> Corrected `@since 2.2` to `@since 3.1` for API changes

jaxrs-api/src/main/java/jakarta/ws/rs/sse/SseEventSource.java
Should finish resolving issue #606.  This clarifies that `onError` and `onComplete` callbacks should be mutually exclusive.
As this is only clarifying behavior in javadoc, I'd like to fast-track this PR.
It should go into the 3.0 release (master) and the 3.1 release (3.1-SNAPSHOT).  If approved, I'll try to cherry pick this into master.  If that is locked down, then I'll open another PR for master.
@spericas, @asoldano, can you review and approve these changes?
@NicoNes, @reta, I cannot add you as reviewers, but would you also take a look to confirm your approval of these changes?
Thanks, Andy
=> [#606] Clarify when to call onError vs onComplete

jaxrs-spec/src/main/asciidoc/chapters/environment/_javaee.adoc
This partially addresses issue #835, updating the spec to clarify that the CDI integration requirements do not apply to resources or providers returned from the `getSingletons` method.
This should also be pushed to 3.1-SNAPSHOT branch.
=> [#835] Clarify injection wrt `getSingletons`

jaxrs-api/src/main/java/jakarta/ws/rs/core/Application.java
Resolves part 2 (of 2) of #835 - this deprecates the `getSingletons` method of `Application`.
=> [#835] Deprecate getSingletons

jaxrs-spec/src/main/asciidoc/chapters/appendix/_bibliography.adoc, jaxrs-spec/src/main/asciidoc/chapters/asynchronous_processing/_server_api.adoc, jaxrs-spec/src/main/asciidoc/chapters/validation/_annotations_and_validators.adoc
According to the issue  Spec: Todo  #804 , I removed the last reference to JSR within the specification document. 
In the discussion #843 we deiced that Expert Group Members and Acknowledgements may stay as-is.
=> Removed references to JSRs

examples/pom.xml, examples/src/main/java/jaxrs/examples/client/BasicExamples.java, examples/src/main/java/jaxrs/examples/client/spec/SpecExamples.java, examples/src/main/java/jaxrs/examples/client/validator/NotNull.java, examples/src/main/java/jaxrs/examples/client/validator/Pattern.java, examples/src/main/java/jaxrs/examples/client/validator/ValidatorExample.java, examples/src/main/java/jaxrs/examples/link/ResourceExample.java, examples/src/main/java/jaxrs/examples/link/clusterservice/Cluster.java, examples/src/main/java/jaxrs/examples/link/clusterservice/Machine.java, examples/src/main/java/jaxrs/examples/sse/ItemStoreResource.java, examples/src/main/java/jaxrs/examples/sse/ServerSentEventsResource.java, jaxrs-api/pom.xml, jaxrs-api/src/main/java/jakarta/ws/rs/core/Link.java, jaxrs-api/src/main/java/module-info.java, jaxrs-api/src/test/java/jakarta/ws/rs/core/JaxbLinkTest.java
This change updates the JAXB and Activation API dependencies to the Jakarta EE 9 levels - using release candidates for now. This change should be considered a work in progress until the JAXB-RI is also published at the EE 9 level.  Until then the JaxbLinkTest unit test will fail.
Feedback welcome, but no need to approve until the JAXB-RI change is made.
Thanks!
This will resolve issue #845 - though we should leave the issue open until we can pull in GA releases as opposed to release candidates.
=> [#845] Update API dependencies for JAXB+Activation

jaxrs-api/src/main/java/jakarta/ws/rs/core/Link.java, jaxrs-spec/src/main/asciidoc/chapters/appendix/_bibliography.adoc, jaxrs-spec/src/main/asciidoc/chapters/appendix/_changes-since-2.2-snapshot.adoc, jaxrs-spec/src/main/asciidoc/chapters/environment/_javaee.adoc, jaxrs-spec/src/main/asciidoc/chapters/providers/_contextprovider.adoc, jaxrs-spec/src/main/asciidoc/chapters/providers/_entity_providers.adoc
Modifications to the spec doc and javadoc that indicate that JAXB is optional.  Where possible, I tried to keep the language consistent with JSON-P / JSON-B - i.e. if the product supports JSON-B, then it must have a built-in entity provider to handle JSON requests - likewise for JAXB / XML.  
This change is targeted for the `master` branch (3.0), and should also go into the `3.1-SNAPSHOT` branch.
Fixes #815
=> [#815] Indicate that JAXB is optional

.travis.yml
This PR provides all needed changes to also build on JDK 14:
- Travis CI uses Open JDK 14
- Fixing Travis Warning: Removing 'sudo' clause
- Fixing Travis Info: Adding 'os' clause
=> Additionally building on JDK 14

examples/pom.xml, jaxrs-api/pom.xml, jaxrs-spec/pom.xml
3.0.0-M1 is already published to Maven Central, so the *current* version of `master` MUST be `3.0.0-SNAPSHOT` again to prevent confusion when building the source locally.
(In fact, this should be done *immediately* after a version was published)
=> Version: 3.0.0-M1 -> 3.0.0-SNAPSHOT

.travis.yml
This PR provides all needed changes to also build on JDK 15:
- Travis CI uses Open JDK 15
=> Additionally building on JDK 15

examples/pom.xml, examples/src/main/java/jaxrs/examples/async/LongRunningEjbResource.java, examples/src/main/java/jaxrs/examples/filter/caching/ServerCachingFilter.java, examples/src/main/java/jaxrs/examples/filter/compression/GzipEntityInterceptor.java, examples/src/main/java/jaxrs/examples/filter/logging/LoggingFilter.java, examples/src/main/java/jaxrs/examples/sse/ServerSentEventsResource.java, jaxrs-api/pom.xml, jaxrs-api/src/main/java/jakarta/ws/rs/Priorities.java, jaxrs-api/src/main/java/jakarta/ws/rs/client/ClientRequestFilter.java, jaxrs-api/src/main/java/jakarta/ws/rs/client/ClientResponseFilter.java, jaxrs-api/src/main/java/jakarta/ws/rs/container/ContainerRequestFilter.java, jaxrs-api/src/main/java/jakarta/ws/rs/container/ContainerResponseFilter.java, jaxrs-api/src/main/java/jakarta/ws/rs/core/Configurable.java, jaxrs-api/src/main/javadoc/overview.html, jaxrs-api/src/test/java/jakarta/ws/rs/core/JaxbLinkTest.java
This pull request contains the following changes:
* Update all Jakarta dependencies to their latest versions
* Migration of `javax.ejb` imports to `jakarta.ejb`
* Migration of `javax.annotation` imports and other references to `jakarta.annotation`
* Removed `@Ignore` from `JaxbLinkTest` (see #846)
* Fixed JAX-RS package names in `overview.html`
=> Update Jakarta dependencies to latest versions

jaxrs-spec/src/main/asciidoc/spec.adoc
Many of the math expressions (especially in section 3.7.2) are broken in the output. See the following screenshot for an example:
Setting the `stem` AsciiDoctor attribute enables support for such expressions and fixes the output. See the following screenshot of the updated output:
Please note that this only fixes the HTML output. The PDF file is still broken as it doesn't support the `stem` attribute. However, there seems to be a AsciiDoctor plugin which allows to fix the math expressions also in the PDF files. However, this should be addressed in a subsequent pull request.
=> Set stem attribute to fix math expressions in HTML output

jaxrs-api/pom.xml, jaxrs-api/src/main/javadoc/resources/EFSL.html, jaxrs-spec/src/main/asciidoc/chapters/license/_license-efsl.adoc
This pull request applies the changes requested in #871.
Please note that the configuration of the javadocs plugin was broken, as it didn't include the `EFSL.html `. This has been fixed as part of the PR.
Please review the changes carefully. I'm not 100% sure if everything is fine this way, but the changes are essentially the same as for the EJB spec.
=> Update EFSL for Specifications and Javadoc

jaxrs-api/src/main/java/jakarta/ws/rs/core/NewCookie.java, jaxrs-api/src/test/java/jakarta/ws/rs/core/NewCookieTest.java
This pull request addresses #862 by adding support for the `SameSite` cookie attribute to the `NewCookie` class.
A few notes:
* I had to add two new constructors to the `NewCookie` class. This diff is a bit hard to read, but the general structure of the class is unchanged.
* There is a new enum `SameSite` which defines all possible values for the `SameSite` attribute. The enum is currently an inner class of `NewCookie`.
* The `NewCookie` class is not mentioned in the spec document at all, so there are no changes necessary
Please refer to eclipse-ee4j/servlet-api#271 for the pull request for adding support for `SameSite` to the Jakarta Servlet API.
Feedback welcome!
=> Add support for SameSite cookie attribute to NewCookie class

jaxrs-api/pom.xml
Removed POM parts already defined in parent:
1. release profile is redundant, parent defines oss-release profile with everything set properly to use gpg and jakarta.oss.sonatype.org
2.  repositories section for jakarta.oss.sonatype.org is defined in parent for both snapshots and staging builds
3. maven-deploy-plugin and maven-release-plugin are set properly in parent
4. distributionManagement is also defined in parent pom
Release is done in 2 steps:
1. mvn deploy -Poss-release,staging
2. release artifact from staging repository to Maven Central when all tests passed and all release related paperwork is done too
- parent pom contains all required setup
I can modify all release cycle related jobs to work properly with parent POM setup.
=> Added parent pom: org.eclipse.ee4j:project:1.0.6

jaxrs-spec/src/main/asciidoc/chapters/providers/_contextprovider.adoc, jaxrs-spec/src/main/asciidoc/chapters/providers/_entity_providers.adoc, jaxrs-spec/src/main/asciidoc/chapters/resources/_determine_response_type.adoc, jaxrs-spec/src/main/asciidoc/chapters/resources/_mapping_requests_to_java_methods.adoc
I spent quite some time today and compared the current HTML version of the spec with the old JAX-RS 2.1 spec document. Especially the chapters containing many math expressions. I found many formatting issues, broken references and invalid AsciiDoc content, mostly caused by the automatic conversion from LaTeX to AsciiDoc.
This pull requests contains fixes for all the issues I discovered. Please note that I just reviewed a few sections (but IMO the most relevant ones, especially section 3.7). So there may be many other issues which nobody noticed so far.
I created PDF versions from the rendered HTML, so I could upload the resulting files to a PDF compare service to help you with your review. The diff is not perfect, but I guess it will be helpful to understand which parts were broken.
You …
=> Fix for various spec document formatting issues

jaxrs-spec/src/main/asciidoc/chapters/appendix/_bibliography.adoc, jaxrs-spec/src/main/asciidoc/chapters/introduction/_introduction.adoc, jaxrs-spec/src/main/asciidoc/chapters/introduction/_status.adoc
Another pull request for cleaning up the spec document:
* References to other Jakarta specs have been updated to the jakarta namespace version (corresponding new major version)
* The "Status" section has been updated (spec version, mailing list, URLs, etc.)
* The reference to the "REST Wiki" has been removed (broken link, website seems to be gone)
=> Updated references to Jakarta specs and adjusted status section

jaxrs-api/src/main/java/jakarta/ws/rs/WebApplicationException.java, jaxrs-api/src/test/java/jakarta/ws/rs/SerializationTest.java
By marking the Response object as transient, since Response isn't
serializable
=> Make WebApplicationException serializable

jaxrs-spec/src/main/asciidoc/chapters/introduction/_project_team.adoc
Previous versions of the spec contained a list of all expert group members in the introduction chapter. I guess it makes sense to continue with this. Therefore, I added this list to the document.
Three weeks ago [I asked the committers on the mailing list](https://www.eclipse.org/lists/jaxrs-dev/msg00829.html) how they want to be listed, but this request was ignored by 90% of the committers. Only 2(!) of 20 committers responded to my mail. However, I added a few more committers for which I know the company they represent. All other committers can add themselves in a subsequent pull request if they want to be listed.
=> Add list of current committers to the spec document

jaxrs-api/src/test/java/jakarta/ws/rs/core/AbstractMultivaluedMapTest.java, jaxrs-api/src/test/java/jakarta/ws/rs/core/CacheControlTest.java, jaxrs-api/src/test/java/jakarta/ws/rs/core/CookieTest.java, jaxrs-api/src/test/java/jakarta/ws/rs/core/EntityTagTest.java, jaxrs-api/src/test/java/jakarta/ws/rs/core/GenericEntityTest.java, jaxrs-api/src/test/java/jakarta/ws/rs/core/GenericTypeTest.java, jaxrs-api/src/test/java/jakarta/ws/rs/core/MediaTypeTest.java, jaxrs-api/src/test/java/jakarta/ws/rs/core/MultivaluedHashMapTest.java, jaxrs-api/src/test/java/jakarta/ws/rs/core/NewCookieTest.java, jaxrs-api/src/test/java/jakarta/ws/rs/core/RxClientTest.java, jaxrs-api/src/test/java/jakarta/ws/rs/core/VariantTest.java, jaxrs-api/src/test/java/jakarta/ws/rs/ext/RuntimeDelegateTest.java
This PR simply removes compiler warnings and `System.out.println` statements from the unit tests.
There are some ignored tests that if the `@Ignore` annotation is removed would still write to System.out, so I added "TODO" comments to change those at that point - I'm not sure, but I think the intent of those tests was to write to STDOUT and then read the output for test verification.  If so, then an in-memory stream might be preferable.
Since this only affects unit tests (not spec or API), I would like to request fast-track approval for this PR.
=> Remove compiler warnings a sysouts in unit tests

jaxrs-api/src/main/java/jakarta/ws/rs/CookieParam.java, jaxrs-api/src/main/java/jakarta/ws/rs/FormParam.java, jaxrs-api/src/main/java/jakarta/ws/rs/HeaderParam.java, jaxrs-api/src/main/java/jakarta/ws/rs/MatrixParam.java, jaxrs-api/src/main/java/jakarta/ws/rs/QueryParam.java, jaxrs-spec/src/main/asciidoc/chapters/appendix/_changes-since-3.0-release.adoc, jaxrs-spec/src/main/asciidoc/chapters/resources/_resource_field.adoc
Fixes #890 - updates to spec and javadoc enabling users to specify array types as parameters.
The javadoc contained this text: "The resulting collection is read-only."  I left it alone, but I'm not sure that I like it... We could remove that text or re-word it to something like "If it is a `List`, `Set` or `SortedSet` it will be read-only" to avoid any confusion about "read-only arrays". 
Also, I think "read-only" is not the right word here - it should probably be "immutable" or "unmodifiable". "Read-only" implies (to me) that the objects in the collection cannot be modified, but we cannot really guarantee that.  IIUC, the intent is to tell the user that they can't change things like the order of the collection - or the number of entries, etc. By Java Collections terminology, that would …
=> [#890] All array types to be used as parameters

jaxrs-spec/src/main/asciidoc/chapters/appendix/_change-log.adoc, jaxrs-spec/src/main/asciidoc/chapters/appendix/_changes-since-2.1-release.adoc
- Changes 2.2-SNAPSHOT to 2.1 Release
- Adds the  package changes and getSingletons updates to the "since 2.1 release" release notes.
This change should go into master (3.0) and 3.1-SNAPSHOT.
Once approved, I will plan to manually merge into the 3.1-SNAPSHOT stream.
=> Update release notes

.travis.yml, jaxrs-api/pom.xml
Updating dependencies to use final version of JAXB and Activation from staging. We need -Pstaging. Will fast track.
=> Updating dependencies to use final version of JAXB and Activation

jaxrs-api/pom.xml
Use Jakarta in title (only) and update version number in Javadocs. Fast track.
=> Use Jakarta in title and update version number in Javadocs

jaxrs-spec/src/main/asciidoc/chapters/providers/_entity_providers.adoc
Fixes #909. Confirmed that this is a Java SE class: https://docs.oracle.com/en/java/javase/11/docs/api/java.xml/javax/xml/transform/Source.html
This too, really ought to be fast-tracked, but it is a spec change... I think we ought to add a clause for fast-tracking trivial bug fixes to avoid waiting two weeks for obvious fixes (i.e. fixing typos, etc.), but for now, I can wait.  :)
=> [#909] Rename Java SE XML transform class in spec

jaxrs-api/pom.xml, jaxrs-api/src/main/java/module-info.java
Fixes #907.  The change to the surefire line is to ensure that Jakarta XML Binding APIs are present for unit testing. This will make the depending on XML Binding optional in both JPMS and OSGi environments.
I'd like to ask for fast-track approval on this, but I'm not sure if it qualifies or not.  The pom.xml change should qualify, but possibly the module-info.java file is considered part of the API?  I think we'll need this change in before we can release 3.0, so the sooner it gets in the better, but I don't want to thwart our process.
=> [#907] Make XML Bind pkgs optional for JPMS/OSGi

.travis.yml
This PR provides all needed changes to also build on JDK 16:
- Travis CI uses Open JDK 16
=> Additionally building on JDK 16

examples/src/main/java/jaxrs/examples/link/ResourceExample.java, jaxrs-api/src/main/java/jakarta/ws/rs/core/Link.java, jaxrs-spec/src/main/asciidoc/chapters/appendix/_changes-since-3.0-release.adoc
Deprecates the JAXB inner classes in the Link class, and modifies the example code use JSON instead of XML so as to avoid any dependencies on JAXB / Jakarta XML Binding. 
This closes #853.
=> [853] Deprecate Link JAXB inner classes

jaxrs-spec/src/main/asciidoc/chapters/appendix/_changes-since-3.0-release.adoc
Added to history that we introduced `#hasProperty(String)` since release 3.1.
=> [Spec] New method `#hasProperty(String)`

jaxrs-spec/src/main/asciidoc/chapters/appendix/_changes-since-3.0-release.adoc, jaxrs-spec/src/main/asciidoc/chapters/applications/_publication.adoc
Core description of the portable Java SE bootstrap for HTTP servers embedded in a compliant implementation supported since Jakarta RESTful Web Services 3.1.
**The underlying Java code already exists in `master`. This PR *only documents* this already existing feature.**
=> [Spec] Java SE Bootstrap

jaxrs-spec/src/main/asciidoc/chapters/appendix/_changes-since-3.0-release.adoc
Mentioning the change done by PR #810 in the history chapter of the spec.
**The underlying Java code already exists in `master`. This PR *only documents* this already existing feature.**
=> [Spec] History: Mention Response.created(URI) (PR 810)

jaxrs-api/src/main/java/jakarta/ws/rs/core/HttpHeaders.java
Fixes #944 - updates the javadoc to indicate that `getRequestHeader(name)` will return null if the header does not exist.
=> [944] Clarify HttpHeaders.getRequestHeader(String name) javadoc if header doesn't exist

jaxrs-spec/src/main/asciidoc/chapters/appendix/_changes-since-2.0-early-draft-second-edition.adoc, jaxrs-spec/src/main/asciidoc/chapters/appendix/_changes-since-2.0-early-draft.adoc, jaxrs-spec/src/main/asciidoc/chapters/appendix/_headersupport.adoc, jaxrs-spec/src/main/asciidoc/chapters/client_api/_client-targets.adoc, jaxrs-spec/src/main/asciidoc/chapters/client_api/_configurable_types.adoc, jaxrs-spec/src/main/asciidoc/chapters/client_api/_invocations.adoc, jaxrs-spec/src/main/asciidoc/chapters/environment/_environment.adoc, jaxrs-spec/src/main/asciidoc/chapters/environment/_javaee.adoc, jaxrs-spec/src/main/asciidoc/chapters/filters_and_interceptors/_binding.adoc, jaxrs-spec/src/main/asciidoc/chapters/providers/_entity_providers.adoc, jaxrs-spec/src/main/asciidoc/chapters/resources/_uritemplates.adoc
- Fixes extraneous code outside of code block
- Fixes several broken links
- In-line code notation
=> General style improvements in spec doc

jaxrs-api/src/main/java/jakarta/ws/rs/core/Context.java, jaxrs-spec/src/main/asciidoc/chapters/appendix/_changes-since-3.0-release.adoc, jaxrs-spec/src/main/asciidoc/chapters/introduction/_status.adoc
New section about support for @Context injection in future versions. In preparation for changes in 4.0.
=> New section about support for @Context injection in future versions

.travis.yml, Jenkinsfile, jaxrs-api/src/test/java/jakarta/ws/rs/SeBootstrapTest.java, jaxrs-tck/pom.xml, jaxrs-tck/src/main/java/jakarta/ws/rs/tck/sebootstrap/SeBootstrapIT.java, jaxrs-tck/src/main/java/jakarta/ws/rs/tck/uribuilder/UriBuilderIT.java, jersey-tck/README.md, jersey-tck/pom.xml
This PR is a **draft** for a new TCK **only** covering post-3.0 additions to the Jakarta REST specifiction.
In particular it currently **only** contains **some** tests as a proof-of-concept. Hence it is neither complete nor intended to be actually merged *as-is*. Certainly this PR MAY be used as a fallback in case no *better* solution is found until deadline.
My proposal is to keep the original Platform TCK as-is, and use this PR as a *starting-point* for a second TCK with anything post-3.0, but not to import anything from the Platform TCK into this new TCK *for some time*, so we can decide *later* whether we live forever with two TCKs or whether we rebuild the existing tests in the new TCK. This scenario allows *every* contributor to write new tests **at once** without *any* learning …
=> TCK tests for Java SE Bootstrap API (and other post-3.0 additions)

pom.xml
This minimal multi-module POM allows convenient use of Maven to do things *on the root dir* like...
* ...build API and Examples in a single line by only naming the "last one" in the chain: `mvn -am -pl examples compile`
* ...build API, Spec, TCK, Examples... in one turn: `mvn package`
* ...change the API, compile the TCK, and run the TCK against Jersey in a single shot: `mvn -am -pl jersey-tck verify`
* ...reclaim lots of disk space: `mvn clean`
* ...and much more...
This makes working with our code base easier, so please review and vote!
**As these are no API changes, this is a fast-track review period of just one day as per our [committer rules](https://github.com/eclipse-ee4j/jaxrs-api/wiki/Committer-Conventions#minimum-length-of-review-period-before-merge--close-of-prs-and-closing-of-i …
=> Minimal multi-module pom to allow "mvn -am -pl" builds

jaxrs-spec/src/main/asciidoc/chapters/appendix/_changes-since-3.0-release.adoc, jaxrs-spec/src/main/asciidoc/chapters/resources/_declaring_method_capabilities.adoc, jaxrs-spec/src/main/asciidoc/chapters/resources/_mapping_requests_to_java_methods.adoc
Clarify matching rules in the case where Content-Type and/or Accept headers are absent. Prompted by discussion in issue #970 and some potential ambiguity in implementations.
=> Clarify matching rules 

jaxrs-spec/src/main/asciidoc/chapters/appendix/_changes-since-3.0-release.adoc, jaxrs-spec/src/main/asciidoc/chapters/providers/_entity_providers.adoc
Adding minimum spec text to enforce respect of `ContextResolver<Jsonb>` as commonly discussed in #742 as an initial proposal.
Please discuss and vote. :-)
Closes #742
=> [742] Mandate usage of JSON-B instance provided by user's ContextResolver<Jsonb>

.travis.yml
With the current LTS strategy, only Java SE versions 8, 11, and 16 are currently supported (and 16 will soon give way to 17 - 16 is not LTS, while 17 is).  As such, I'd like to reduce CI cycles by removing out-of-support JDKs from the CI pipeline.
This isn't an API/spec/TCK change, so it should be fast-tracked.
=> Remove out-of-support JDKs from CI

etc/config/checkstyle.xml, examples/pom.xml, jaxrs-api/pom.xml
This PR re-enables JavaDoc checks previously commented out due to a known issue with Checkstyle.
Apparently the issue does not occur anymore with latest Checkstyle 8.43, at least in my environment (Windows 10, OpenJDK 16) I could not reproduce the mentioned problem.
I'd like to propose that we adopt this PR, even if there never had been an official solution to the Checkstyle issue. If the problem pops up again, we can simply comment out the JavaDoc check again.
=> Version Bump: Checkstyle 8.43

jaxrs-api/src/main/java/jakarta/ws/rs/core/EntityPart.java
These were the only lines  that raised Javadoc warnings. There were other warnings, that I could look into, but these were the only Javadoc specific ones I saw.
Closing #979 
=> Fixed Javadoc Warnings

jaxrs-tck/src/main/java/jakarta/ws/rs/tck/sebootstrap/SeBootstrapIT.java, jaxrs-tck/src/main/java/jakarta/ws/rs/tck/uribuilder/UriBuilderIT.java
* Removed unecessary exceptions from method throws clause
* Resolves issue of missing javadoc for exception
* If those exceptions are included for a reason, the PR can be rejected/closed
=> Fix Javadoc Issues In Tck

Jenkinsfile
Nightly builds on Jenkins have been failing for a while. Setting JDK to latest 11.
=> Set JDK version to 11 on Jenkins

etc/config/checkstyle.xml, examples/pom.xml, jaxrs-api/pom.xml
This PR fixes a build fail caused by PR 983.
In contrast to the alternative [PR 999](https://github.com/eclipse-ee4j/jaxrs-api/pull/999), *this* is an actual **fix** instead of a simple undo: Both, Maven Checkstyle Plugin and Checkstyle, are updated to the latest version, so the build is running fine again (this implies minor modifications to the checkstyle configuration as part of this PR).
=> Version Bump: Maven Checkstyle Plugin 3.1.2 + Checkstyle 8.44

jaxrs-api/pom.xml
Collection of useful steps towards API v3.1
=> Preparing API POM for v3.1

jaxrs-spec/pom.xml, jaxrs-spec/src/main/asciidoc/chapters/appendix/_changes-since-3.0-release.adoc, jaxrs-spec/src/main/asciidoc/chapters/introduction/_status.adoc
Collection of useful steps towards spec doc v3.1
=> Preparing spec doc v3.1

examples/pom.xml, jaxrs-api/pom.xml, jaxrs-api/src/main/java/jakarta/ws/rs/core/EntityPart.java, jaxrs-spec/pom.xml, jaxrs-tck/pom.xml, jersey-tck/pom.xml, pom.xml
Cleanup of pom names, and changes to relative paths to avoid warnings when building modules. Some minor updates to Javadocs to avoid warnings as well.
Requesting fast track.
=> Cleanup of pom names and relative paths to avoid warnings

jaxrs-spec/src/main/asciidoc/chapters/introduction/_project_team.adoc
This section of the spec is intended to provide a reference whom to call with question of the *current* spec and API revision, so it makes no sense to keep people listet not having contributed in any noticeable form *for many months*.
Either we agree on *frequent* updates to this list in the spec, or we replace the names with a link to the Github statistics.
=> Removing inactive committers

jaxrs-tck/src/main/java/jakarta/ws/rs/tck/uribuilder/UriBuilderIT.java
This PR makes two TCK test changes:
(1) Changing test to verify scheme-only URI throws UriBuilderException - it is possible to create an "empty" URI (i.e. `URI.create("")` and RESTEasy allows `UriBuilder.newInstance().build()` to execute without throwing a `UriBuilderException`, but a scheme-only URI is not allowed (i.e. `UriBuilder.newInstance().scheme("http").build()` / `URI.create("http:")`).
(2) Adding new test for checking `IllegalArgumentException` is thrown for unresolved template variables.
=> Update UriBuilderIT test

jaxrs-api/src/main/java/jakarta/ws/rs/core/Response.java
This PR is the follow-up to the [issue](https://github.com/eclipse-ee4j/jaxrs-api/issues/706) and  [discussion](https://github.com/eclipse-ee4j/jaxrs-api/issues/736) we had with @ronsigal.
To sum up it was about adding a method in the `Response` class to know when a response instance is closed. So that we no longer need to write code like:
```
try {
if (response.getEntity() != null) return response;
}
catch(IllegalStateException ise) {
// IllegalStateException from ClientResponse.getEntity() means the response is closed and got no entity
} 
```
but instead: 
```
if (!response.isClosed() && response.getEntity() != null) {
return response;
}
```
I agree that the default implementation I proposed is a bit weird, not intuitive etc . I did it so that vendors don't need to make changes on their …
=> Add Response.isClosed()

etc/config/checkstyle.xml, examples/src/main/java/jaxrs/examples/client/BasicExamples.java, jaxrs-api/src/main/java/jakarta/ws/rs/core/Cookie.java, jaxrs-api/src/main/java/jakarta/ws/rs/core/NewCookie.java, jaxrs-api/src/test/java/jakarta/ws/rs/core/CookieTest.java, jaxrs-api/src/test/java/jakarta/ws/rs/core/NewCookieBuilderTest.java, jaxrs-api/src/test/java/jakarta/ws/rs/core/NewCookieTest.java, jaxrs-spec/src/main/asciidoc/chapters/appendix/_changes-since-3.0-release.adoc
A proposal to use builder pattern much more developer friendly than telescoping constructors in `Cookie` and `NewCookie` .
For example to set a `NewCookie` instance with a name and a `SameSite.LAX` attribute no longer need to do this:
`new NewCookie("name", null, null, null, Cookie.DEFAULT_VERSION, null, DEFAULT_MAX_AGE, null, false, false, SameSite.LAX);`
just do that:
`new NewCookie.Builder("name").sameSite(SameSite.LAX).build();`
=> Cookie Builder

jaxrs-api/pom.xml
These were dropped together with the profiles of the various JDK's and can result on a Maven warning (see pipeline) or worse failure to compile if picking up an old surefire version (was able to reproduce this locally).
Requesting fast track.
=> Set explicit versions for compiler and surefire plugins

jaxrs-spec/src/main/asciidoc/chapters/resources/_declaring_method_capabilities.adoc, jaxrs-spec/src/main/asciidoc/chapters/resources/_mapping_requests_to_java_methods.adoc
Forcing the default content type of application/octet-stream is problematic in practice. It breaks the common use case of inheriting class-level `@Consumes` annotations on `@GET` methods. Text now also clarifies that specific matching case. See discussion in Issue #970. 
Requesting fast track.
=> Reverts changes introduced by PR 972

examples/pom.xml, jaxrs-api/pom.xml, jaxrs-spec/pom.xml, jaxrs-tck/pom.xml, pom.xml
Fixed pom parent-child relationship to make sure deploy works on Jenkins nightly builds. Nightly builds have been failing for a while due to misconfiguration problems. See https://ci.eclipse.org/jaxrs/job/Nightly%20Build/job/master/
Some minor re-formatting too. Fast track.
=> Fixed pom parent-child relationship 

Jenkinsfile, examples/pom.xml, pom.xml
Moved distribution management for Eclipse's content repos to main pom. Protected release repo using a profile to avoid accidental pushes.
=> Moved distribution management to main pom

jaxrs-api/src/main/java/jakarta/ws/rs/core/Response.java
This adds the status code _[308 Permanent Redirect](https://tools.ietf.org/html/rfc7538)_ as discussed in #993.
One possible application would be if part of an API has been permanently moved to another URI.
=> Add status code 308 Permanent Redirect

jaxrs-api/src/main/java/jakarta/ws/rs/core/Response.java
This adds the status code _[300 Multiple Choices](https://tools.ietf.org/html/rfc7231#section-6.4.1)_ as discussed in #993.
I could see reactive content negotiation being used in a REST service, be it about language, media type or something else. This is why I think we should include this.
=> Add status code 300 Multiple Choices

pom.xml
The purpose of the PR is to separate modules in the parent pom into profiles, which is good for releases to the maven staging/central. 
The issue is that when releasing API (from the jaxrs-api module) the parent pom shall be published into staging/central as well. 
So, when the forward approach is applied (the project is being built from its root folder) all modules are being compiled. But when it comes to releasing where only particular modules are being released related parent pom becomes invalid from the point of modules view. 
In the PR there are 2 profiles with 3 and 1 modules respectively. The module with 3 profiles contains references to API, TCK, and examples. And the module with one module relates to the spec which is never being published to staging/central. 
Thus when the …
=> separate modules into profiles

jaxrs-tck/src/main/java/jakarta/ws/rs/tck/common/JAXRSCommonClient.java, jaxrs-tck/src/main/java/jakarta/ws/rs/tck/spec/resourceconstructor/JAXRSClientIT.java
This change adds the beans.xml file to the deployed WAR for the `resourceconstructor` test.  The beans.xml was added as part of challenge issue #938, but from my testing it was not added to the WAR file.  This change fixes that.
Since this only fixes a bug in a TCK test and makes no changes to spec or API, I'd like to request fast-track.
=> Ensure resourceconstructor test includes beans.xml

.github/workflows/maven-package.yml
Adopt OpenJDK is called Eclipse Temurin since a while. There will be no new JDKs published with the adopt label, but only with the temurin label. So our builds should use Temurin instead of Adopt now. 
=> Adopt OpenJDK now is Eclipse Temurin

.github/workflows/maven-package.yml
This PR replaces the custom configuration "package --file pom.xml" by the usual "verify" configuration which is more stereotypical in Maven projects, which allows to run integration tests, and aligns Github Actions with what we had in Travis CI.
=> mvn verify instead of package --file pom.xml

jaxrs-api/src/main/java/jakarta/ws/rs/client/ResponseProcessingException.java, jaxrs-api/src/main/java/jakarta/ws/rs/core/Cookie.java, jaxrs-api/src/main/java/jakarta/ws/rs/core/PathSegment.java, jaxrs-api/src/main/java/jakarta/ws/rs/sse/SseEventSource.java, jaxrs-api/src/main/java/module-info.java
This PR fixes warnings in the JAX-RS API's JavaDocs.
=> [#979] Fixed JavaDoc Warnings

jersey-tck/pom.xml
`mvn --file jersey-tck/pom.xml verify` fails on JRE 17.
The reason is that it uses GlassFish 6.1.0, which is not compatible with JRE 17 (uses `Unsafe` class).
The solution is to replace it by GlassFish 6.2.3.
=> Fixed: jersey-tck fails on JRE 17 due to Unsafe class

jaxrs-tck-docs/JAXRSTCK3.1-ReleaseNotes.html, jaxrs-tck-docs/tckbundle.sh, jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/jaxrs31/spec/extensions/DynamicFeatureResource.java, jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/jaxrs31/spec/extensions/JAXRSClientIT.java, jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/jaxrs31/spec/extensions/TSAppConfig.java, jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/jaxrs31/spec/extensions/TckDynamicFeature.java, jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/jaxrs31/spec/extensions/TckFeature.java
Requesting fast track as it involves : 
- TCK changes to correct the package names of newly added tests in jaxrs31/ folder.
- correct the EPL TCK bundle generation script.
- update the total test count in Release Notes as 2795 (this includes the test in this PR and PR 976)
@jansupol @spericas
=> TCK changes : Move new tests to renamed package, fix epl tck bundle generation

pom.xml
This PR proposes the introduction of a new Maven profile `jaxrs.jerseytck.build` to make the testing of new TCK tests easier.
*Without* this PR, the current way of developing new TCK tests is to *install* the modified TCK into the local Maven repository, then run jersey-tck as a proof-of-concept (like a beta-test for the new TCK test). The installation in local Maven repository is mandatory, as jersey-tck is not a module of the JAX-RS top-level POM, hence would not see the current TCK changes otherwise.
Installing work-in-progress in the local Maven repository is very bad, as several parallel projects could never rely on "their" current state of the TCK: You cannot test multiple TCK changes in parallel branches, as only one version of the TCK can be installed at any time.
The way to go …
=> Maven profile jaxrs.jerseytck.build

jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/common/util/JaxrsUtil.java, jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/sebootstrap/SeBootstrapIT.java, jaxrs-tck/src/test/java/ee/jakarta/tck/ws/rs/common/util/JaxrsUtilTest.java
This PR removes an unnecessary workaround: There is not need to check the port number, as nobody ever has seen any JRE on any OS that returned a non-ephemerial port. Oracle's OpenJDK team even disputes that this could happen ever, and there is no proof that there would be a bug. Hence we should not fix something that is not broken.
=> Removed unnecessary workarond for ephemerial port

jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/api/rs/core/linkjaxbadapter/JAXRSClientIT.java, jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/jaxrs21/ee/sse/sseeventsink/JAXRSClientIT.java, jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/jaxrs21/ee/sse/sseeventsource/JAXRSClientIT.java, jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/spec/provider/standardhaspriority/JAXRSClientIT.java
While running the TCK without Jakarta XML Binding present, we've been running into failures with these tests that were previously excluded in the Jakarta EE Platform TCK.
=> exclude additional Jakarta XML Binding tests that were previously excluded in the Jakarta EE Platform TCK

jaxrs-tck-docs/tckbundle.sh, jaxrs-tck-docs/userguide/pom.xml, jaxrs-tck-docs/userguide/src/main/jbake/content/attributes.conf, jaxrs-tck/pom.xml, jersey-tck/pom.xml
This is to append the tck versions from 3.1.0 to 3.1.1 for a new service release. 
The service release of the new TCK needs changes in https://github.com/jakartaee/rest/pull/1117  that is required for core profile going to ballot.
**Requesting fast-track review on this as the changes involved only in tck and new service release is expected that will be used for core profile ballot review.**
cc @jansupol @spericas
=> version changes for tck service release 3.1.1

jaxrs-tck-docs/userguide/src/main/jbake/content/attributes.conf, jaxrs-tck-docs/userguide/src/main/jbake/content/using-examples.inc, jaxrs-tck-docs/userguide/src/main/jbake/content/using.adoc, jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/ee/rs/container/requestcontext/JAXRSClientIT.java, jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/ee/rs/core/securitycontext/basic/JAXRSBasicClientIT.java
Resolves https://github.com/jakartaee/rest/issues/1120 & https://github.com/jakartaee/rest/issues/1121 .
Related Issue : https://github.com/eclipse-ee4j/jakartaee-tck/issues/1097 
Two new test groups (Junit Tags) are created - "security" & "servlet", so that they can be excluded when run against Core profile.
**Requesting fast-track review on this as the changes are involved only in tck. The new service release (3.1.1) of the TCK that will be used for core profile ballot review requires these changes.**
cc  @jansupol @spericas @starksm64 @brideck
=> Create new test groups - security and servlet

jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/ee/rs/container/requestcontext/security/JAXRSClientIT.java
Resolves https://github.com/jakartaee/rest/issues/1121 
Related Issue : https://github.com/eclipse-ee4j/jakartaee-tck/issues/1097
More tests are added to test group (Junit Tags) "security"  that was missed in https://github.com/jakartaee/rest/pull/1122. 
**Requesting fast-track review on this as the changes are involved only in tck. The new service release (3.1.1) of the TCK will be updated with this change and will be used for core profile ballot review.**
cc @brideck @jansupol @arjantijms @spericas @starksm64
=> Update testgroup "security" with more tests

jaxrs-tck-docs/userguide/src/main/jbake/content/using-examples.inc, jaxrs-tck-docs/userguide/src/main/jbake/content/using.adoc, jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/sebootstrap/SeBootstrapIT.java
Fixes https://github.com/jakartaee/rest/issues/1128 
Create new tag 'se_bootstrap' for SE bootstrap tests in ee.jakarta.tck.ws.rs.sebootstrap.SeBootstrapIT.java
cc @spericas @jansupol @jim-krueger @mkarg
=> New tag for SEbootstrap tests - issue 1128

jaxrs-tck-docs/tckbundle.sh, jaxrs-tck-docs/userguide/pom.xml, jaxrs-tck/pom.xml, jersey-tck/pom.xml
This is to append the tck versions from 3.1.1 to 3.1.2 for a new service release.
Requesting fast-track review on this as the changes involved only in tck and new service release is expected soon.
cc @jansupol @spericas @jim-krueger
=> Version changes for tck service release 3.1.2

jaxrs-api/src/main/java/jakarta/ws/rs/client/ClientRequestContext.java, jaxrs-api/src/main/java/jakarta/ws/rs/client/ClientResponseContext.java, jaxrs-api/src/main/java/jakarta/ws/rs/container/ContainerRequestContext.java, jaxrs-api/src/main/java/jakarta/ws/rs/container/ContainerResponseContext.java, jaxrs-api/src/main/java/jakarta/ws/rs/core/HttpHeaders.java
For release 4.0 I'd like to propose a convencience method for response/request contexts which I missed a lot in the past years and which I implemented again and again in multiple ways -- most of them lacking either performance or perfection.
The problem it solves is that it is rather hard to get it perfectly correct checking for items in comma-separated headers - without losing valuable performance.
Example: How to check if there is a `Cache-Control: no-store` value set in case the actual sent headers contains `Cache-Control` multiple times and each of the findings is possibly a comma-separated list? RegEx over getHeaderString() comes into mind, but this is rather slow, as it first concatenates everything just to split it up afterwards. Iterating all findings comes into mind next, which …
=> Convenience method for checking header value lists

jaxrs-api/src/main/java/jakarta/ws/rs/core/MediaType.java
`APPLICATION/SVG+XML` is not recognized by modern browsers, as the official MIME type of SVG graphics is `IMAGE/SVG+XML`.
As least RESTful applications produce SVG at all, it makes not much sense to keep this and add the new variant. Instead, a custom String or a custom library should replace the outdated elements.
=> Deprecating "APPLICATION/SVG+XML" for Removal

jaxrs-tck-docs/TCK-Exclude-List.txt, jaxrs-tck-docs/tckbundle.sh, jaxrs-tck-docs/userguide/pom.xml, jaxrs-tck/pom.xml, jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/ee/rs/core/uriinfo/JAXRSClientIT.java, jersey-tck/pom.xml
Resolves https://github.com/jakartaee/rest/issues/1138 by excluding the test.
This change would be part of the next Jakarta REST TCK maintenance release 3.1.3. 
Update: Added commit to append the TCK version to 3.1.3
Requesting fast-track review on this as the changes involved only in tck and new service release is expected for certifying OpenLiberty.
cc @arjantijms @jansupol @spericas @brideck
=> TCK challenge : exclude getNormalizedUriTest

.github/workflows/maven-package.yml, Jenkinsfile, pom.xml
Fixes #1167
This PR enables compilation of JDK 21 in the release-4.0 branch as proposed in the discussion of https://github.com/jakartaee/rest/issues/1167.
=> Compiling for Java 21

.github/workflows/maven-package.yml
This issue resolved the item "Update README, LICENSE and review all other top-level files" from the Jakarta REST 4.0 Epic.
In fact, all top-level files look good and do not need any changes justified by switching from 3.1 to 4.0 (some other changes might be useful but should go into `master`, or are covered by other PRs already).
The sole change is the correction of the used branch name.
=> Jakarta REST 4.0 Epic: Updating top-level files

jaxrs-spec/pom.xml
This PR updates Asciidoctor to the latest version.
*Note: This PR deliberately does not touch the versions used by the TCK. The reason is that (apparently) the TCK is using other versions. Before aligning the version numbers we need to take care the TCK is fine with them. Hence that goes in a subsequent PR.*
=> Asciidoctor Update

jaxrs-tck-docs/userguide/pom.xml, jaxrs-tck/pom.xml, jersey-tck/pom.xml, pom.xml
This PR updates Maven Plugins to latest versions.
*Note: This PR deliberately does not touch the versions used by the TCK. The reason is that (apparently) the TCK is using other versions. Before aligning the version numbers we need to take care the TCK is fine with them. Hence that goes in a subsequent PR.*
=> Updating Maven Plugins

CONTRIBUTING.md, NOTICE.md, examples/pom.xml, jaxrs-api/pom.xml, jaxrs-api/src/main/java/jakarta/ws/rs/core/CacheControl.java, jaxrs-api/src/main/java/jakarta/ws/rs/core/Cookie.java, jaxrs-api/src/main/java/jakarta/ws/rs/core/EntityTag.java, jaxrs-api/src/main/java/jakarta/ws/rs/core/NewCookie.java, jaxrs-spec/pom.xml, jaxrs-spec/src/main/asciidoc/chapters/introduction/_status.adoc, jaxrs-spec/src/main/asciidoc/spec.adoc, jaxrs-tck-docs/userguide/pom.xml, jaxrs-tck-docs/userguide/src/main/jbake/assets/_config.yml, jaxrs-tck/pom.xml
Since many months the URL to our Github project has changed. Apparently we forgot to reflect this in all the places where we mentioned it. This PR tries to fix this. 😅 
*Note: This PR will fix the master branch. I assume your votes as valid for *any* branch, and will cherry-pick this fix into the release-4.0 and release-3.1.x branches subsequently without filing a new PR.*
=> Replaced GitHub URL from eclipse-ee4j to jakartaee namespace

jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/jaxrs21/ee/sse/ssebroadcaster/JAXRSClientIT.java
=> 1162 sse broadcast test

jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/jaxrs21/ee/sse/ssebroadcaster/JAXRSClientIT.java
When moving fix from test system for #1172 I missed an import and for some reason the maven build done as part of the checks did not flag this.  This PR adds the missing import.
=> fast-track: 1162 sse broadcast test

jaxrs-tck-docs/tckbundle.sh, jaxrs-tck-docs/userguide/pom.xml, jaxrs-tck/pom.xml, jersey-tck/pom.xml
..also adding LICENCE file to tck jar
This is to append the tck version to 3.1.4 for a new service release.
Requesting fast-track review on this as the changes involved only in tck.
cc @jansupol @spericas @jim-krueger
=> version changes for TCK service release 3.1.4

jaxrs-tck-docs/TCK-Exclude-List.txt, jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/ee/rs/container/responsecontext/JAXRSClientIT.java
Resolves https://github.com/jakartaee/rest/issues/1163 by excluding the test.
This change would be part of the next Jakarta REST TCK maintenance release 3.1.4.
Requesting fast-track review on this as the changes made only in tck.
cc @jansupol @spericas @radcortez @jamezp
=> TCK challenge: exclude setEntityStreamTest

_config.yml, apidocs/2.1.6/package-list, apidocs/3.0.0/package-list, apidocs/index.md
PR provides fixes on links to API docs and makes released API docs compatible with references from documentations compiled with JDKs prior to JDK 10. 
As soon as this is only a documentation change (which, however, affects the functionality of the page) I apply for fast-track merging into the gh-pages branch.
=> [gh-pages] Fixes for apidoc references and compatibility with JDK 1.8

examples/src/main/java/jaxrs/examples/resource/SampleResource.java, jaxrs-api/src/main/java/jakarta/ws/rs/BeanParam.java, jaxrs-api/src/main/java/jakarta/ws/rs/Body.java, jaxrs-spec/src/main/asciidoc/chapters/asynchronous_processing/_server_api.adoc, jaxrs-spec/src/main/asciidoc/chapters/resources/_resource_method.adoc
Fixes #1183
Rename the `@Entity` annotation to `@Body` and update references.
=> [1183] - rename Entity annotation to Body

jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/ee/rs/container/responsecontext/ResponseFilter.java
=> TCK Close the original stream of setEntityStream

.github/workflows/maven-package.yml, jaxrs-api/src/main/java/jakarta/ws/rs/container/Suspended.java, jaxrs-api/src/main/java/jakarta/ws/rs/core/Context.java
Deprecate `@Context` and `@Suspended` in release-3.2 in preparation for removal in release-4.0
=> Deprecate both @Context and @Suspended

jaxrs-tck-docs/TCK-Exclude-List.txt, jaxrs-tck-docs/tckbundle.sh, jaxrs-tck-docs/userguide/pom.xml, jaxrs-tck/pom.xml, jersey-tck/pom.xml
This is to append the tck version to 3.1.5 for a new service release. 
The updates are to exclude the challenged tests as in PR https://github.com/jakartaee/rest/issues/1200.
Requesting fast-track review on this as the changes involved only in tck.
cc @jansupol @spericas
=> Version changes for TCK service release 3.1.5

examples/src/main/java/jaxrs/examples/sse/ServerSentEventsResource.java, jaxrs-api/src/main/java/jakarta/ws/rs/sse/SseEventSink.java, jaxrs-tck-docs/TCK-Exclude-List.txt, jaxrs-tck-docs/tckbundle.sh, jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/common/JAXRSCommonClient.java, jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/ee/rs/container/responsecontext/JAXRSClientIT.java, jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/ee/rs/container/responsecontext/ResponseFilter.java, jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/ee/rs/core/uriinfo/JAXRSClientIT.java, jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/jaxrs21/ee/sse/ssebroadcaster/JAXRSClientIT.java, jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/jaxrs21/ee/sse/sseeventsink/CloseResource.java, jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/jaxrs21/ee/sse/sseeventsink/MBWCheckResource.java, jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/jaxrs21/ee/sse/sseeventsink/StageCheckerResource.java, jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/jaxrs21/ee/sse/sseeventsource/MediaTypeResource.java, jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/jaxrs21/ee/sse/sseeventsource/ServiceUnavailableResource.java
Pulled in changes from the following 3.1.x PR's:
https://github.com/jakartaee/rest/pull/1139
https://github.com/jakartaee/rest/pull/1173
https://github.com/jakartaee/rest/pull/1181
https://github.com/jakartaee/rest/pull/1184
https://github.com/jakartaee/rest/pull/1200
Pulled in changes from the following 4.0 PR's:
https://github.com/jakartaee/rest/pull/863
https://github.com/jakartaee/rest/pull/1146
https://github.com/jakartaee/rest/pull/1164
https://github.com/jakartaee/rest/pull/1172
https://github.com/jakartaee/rest/pull/1182
Removed changes from [PR 864](https://github.com/jakartaee/rest/pull/863) since this change is a breaking change and needs to go in a full release.
Still needs fix to [Issue 1138](https://github.com/jakartaee/rest/issues/1138) and then the exclude list can be …
=> Add changes from release-3.1.x and release-4.0 TCK to release-3.2

jaxrs-spec/src/main/asciidoc/chapters/appendix/_change-log.adoc, jaxrs-spec/src/main/asciidoc/chapters/appendix/_changes-since-3.1-release.adoc, jaxrs-spec/src/main/asciidoc/chapters/environment/_javaee.adoc
=> Remove @ManagedBean annotation

jaxrs-spec/pom.xml, jaxrs-tck-docs/userguide/pom.xml, jaxrs-tck/pom.xml, pom.xml
I found these commits I missed that were in release-4.0 and not in main or release-3.2. 
---
The first commit is to fix a bad port which reverted some changes from #1177 
These are from #1170 
This includes a JUnit and mockito upgrades as well. This is a port of #1169
=> fast track: Port missed fixes that were in release-4.0

jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/jaxrs31/ee/multipart/MultipartSupportIT.java
=> fast-track: Add multipart EntityPart tests

jaxrs-tck/pom.xml
This was caused by #1224. Just a minor change from `com/` to `ee/` since the package name starts with `ee`.
=> fast-track: Fix the including of resources in the TCK.

jaxrs-api/src/main/java/jakarta/ws/rs/core/UriInfo.java, jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/jaxrs40/ee/rs/core/uriinfo/JAXRSClientIT.java, jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/jaxrs40/ee/rs/core/uriinfo/TSAppConfig.java, jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/jaxrs40/ee/rs/core/uriinfo/UriInfo40ClientIT.java, jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/jaxrs40/ee/rs/core/uriinfo/UriInfoTestResource.java
Implements #1191 
There can be a discussion of the actual method name, as the proposed name was `getResourceTemplate`, but `getMatchedResourceTemplate` is more aligned with other `matched` methods.
Also, the return type can be in the form of a list, but the discussion was to return a string
=> Added UriInfo#getMatchedResourceTemplate method

jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/ee/resource/webappexception/defaultmapper/DefaultExceptionMapperIT.java, jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/ee/resource/webappexception/defaultmapper/OverriddenDefaultExceptionMapper.java, jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/ee/resource/webappexception/defaultmapper/Resource.java, jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/ee/resource/webappexception/defaultmapper/TSAppConfig.java, jaxrs-tck/src/main/resources/ee/jakarta/tck/ws/rs/ee/resource/webappexception/defaultmapper/web.xml.template
The `nomapper` tests seem to test the default `ExceptionMapper`, however, we could use a test to verify that the default `ExceptionMapper` can be overridden.
This test overrides the default `ExceptionMapper` to return status HTTP 512 instead of HTTP 500 and the test client verifies that status HTTP 512 is returned.
=> fast-track: Add a TCK test to verify that the default ExceptionMapper can be overridden.

jaxrs-spec/src/main/asciidoc/chapters/appendix/_changes-since-3.1-release.adoc, jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/ee/rs/container/requestcontext/RequestFilter.java
Added 4.0 content to the Changes since 3.1 appendix section of the spec.
Added removal of space accidentally added before an EOL in merged PR #1238
=> fast-track: Add 4.0 content to Specification appendix

jaxrs-tck/docs/JAXRSTCK4.0-ReleaseNotes.html, jaxrs-tck/docs/assertions/JAXRSSpecAssertions_3.1.0.xml, jaxrs-tck/docs/assertions/JAXRSSpecAssertions_4.0.0.html, jaxrs-tck/docs/assertions/JAXRSSpecAssertions_4.0.0.xml, jaxrs-tck/docs/index.html, jaxrs-tck/docs/userguide/src/main/jbake/content/attributes.conf, jaxrs-tck/pom.xml
In jaxrs-tck/docs/
- New file JAXRSTCK4.0-ReleaseNotes.html  replacing JAXRSTCK3.1-ReleaseNotes.html with basic changes including version.
- Created new Spec Assertions file JAXRSSpecAssertions_4.0.0.html/xml that has the recent update made to JAXRS:SPEC:131 via https://github.com/jakartaee/rest/pull/1231. Retained JAXRSSpecAssertions_3.1.0.html/xml with contents from release 3.1. Any further update to the spec assertions for release 4.0 can go in JAXRSSpecAssertions_4.0.0.html/xml. 
- index.html and userguide config file jaxrs-tck/docs/userguide/src/main/jbake/content/attributes.conf updated with basic version updates.
- Update jaxrs-tck/pom,xml with latest versions of dependencies.
cc @jim-krueger @spericas @jansupol @jamezp
=> fast-track: TCK documentation and dependency update for 4.0

jaxrs-tck/pom.xml, jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/spec/resource/requestmatching/JAXRSClientIT.java
Resolves https://github.com/jakartaee/rest/issues/1267 by allowing "allow" and "Allow" in header text for [optionsOnSubResourceTest](https://github.com/jakartaee/rest/blob/main/jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/spec/resource/requestmatching/JAXRSClientIT.java#L432)
=> Correct optionsOnSubResourceTest to allow "allow" in header text

jaxrs-tck/src/main/java/ee/jakarta/tck/ws/rs/ee/rs/container/requestcontext/JAXRSClientIT.java
Fixes #1278 
Although there are a couple alternative for fixing the issue identified in #1278, simply changing the case for the Header3 header added in `containsHeaderStringTest` appears to be the simplest solution with the least amount of associated risk.
See #1278 for details.
=> Fix TCK header case issue for ee.jakarta.tck.ws.rs.ee.rs.container.requestcontext.JAXRSClientIT.containsHeaderStringTest

jaxrs-api/src/main/java/jakarta/ws/rs/ext/RuntimeDelegate.java
It is common sense that `synchronized` should only be used *if essentially needed*, as in most scenarios `ReentrantLock` is more efficient.
*Requesting **fast-track** according to our Committer Conventions, as this PR is a non-API, non-spec, non-javadoc change.*
=> Performance: Using ReentrantLock instead of synchronized

jaxrs-api/src/main/java/jakarta/ws/rs/core/Variant.java
TL;DR: This PR internally optimizes the JAX-RS API implementation code by getting rid of `StringWriter` for *purely temporary* use case.
*Requesting **fast-track** according to our Committer Conventions, as this PR is a non-API, non-spec, non-javadoc change.*
For those interested in the details:
* `StringWriter` is implicitly synchronized due to its internal use of `StringBuffer`, while `StringBuilder` is non-synchronized. Using synchronized code in single-threaded contexts is not needed.
* Providing initial content to the constructor reduces number of interally copied bytes on later `append` thanks to bigger upfront buffer allocation.
* Appending `null` automatically appends `"null"`. This is implied by `StringBuilder`, no need for custom code.
* Appending a single `char` is faster than …
=> Performance: Getting rid of temporary internal StringWriter

jaxrs-api/src/main/java/jakarta/ws/rs/client/ClientBuilder.java, jaxrs-api/src/main/java/jakarta/ws/rs/client/FactoryFinder.java, jaxrs-api/src/main/java/jakarta/ws/rs/ext/FactoryFinder.java, jaxrs-api/src/main/java/jakarta/ws/rs/ext/RuntimeDelegate.java, jaxrs-api/src/main/java/jakarta/ws/rs/sse/FactoryFinder.java, jaxrs-tck/src/main/resources/ee/jakarta/tck/ws/rs/signaturetest/jakarta.ws.rs.sig_3.2.0
This PR removes the support for Security Manager.
closes #1262 
*Requesting **fast-track** according to our Committer Conventions, as this PR is a non-API, non-spec, non-javadoc change.*
=> Remove Security Manager

jaxrs-api/src/main/java/jakarta/ws/rs/client/FactoryFinder.java, jaxrs-api/src/main/java/jakarta/ws/rs/ext/FactoryFinder.java, jaxrs-api/src/main/java/jakarta/ws/rs/sse/FactoryFinder.java
This PR internally modernizes the JAX-RS API implementation code by using JDK 7's NIO2 API instead of old-school IO API.
*Requesting **fast-track** according to our Committer Conventions, as this PR is a non-API, non-spec, non-javadoc change.*
=> Modernization: Using NIO2 instead of IO

jaxrs-api/src/main/java/jakarta/ws/rs/core/MediaType.java, jaxrs-api/src/test/java/jakarta/ws/rs/core/MediaTypeTest.java
I like to propose the addition of the new method `MediaType.getCharsetParameter()` which either returns a `Charset` instance, `null`, or throws `UnsupportedCharsetException`.
Rather often I came across code like the following lines (quoted from Jersey) in applications, filters and compliant implementations:
https://github.com/eclipse-ee4j/jersey/blob/b128e9c9e649e96488a9c1d367e4cbae89a9d1d4/core-common/src/main/java/org/glassfish/jersey/message/internal/ReaderWriter.java#L127-L130
```java
public static Charset getCharset(MediaType m) {
String name = (m == null) ? null : m.getParameters().get(MediaType.CHARSET_PARAMETER);
return (name == null) ? StandardCharsets.UTF_8 : Charset.forName(name);
}
```
I do not see any benefit in repeating the obvious again and again, so why not giving away …
=> New method MediaType.getCharsetParameter() returns charset instance or null

jaxrs-api/src/main/java/jakarta/ws/rs/client/ClientRequestContext.java, jaxrs-api/src/main/java/jakarta/ws/rs/client/ClientResponseContext.java, jaxrs-api/src/main/java/jakarta/ws/rs/container/ContainerRequestContext.java, jaxrs-api/src/main/java/jakarta/ws/rs/container/ContainerResponseContext.java, jaxrs-api/src/main/java/jakarta/ws/rs/core/HttpHeaders.java
In [an earlier discussion](https://github.com/jakartaee/rest/pull/1066#issuecomment-1249264250) @jansupol and me proposed to allow specifying the separation character for getHeaderString, as some header values actually may contain commas, so being able to separate them later bears the need to have non-comma separation.
=> Can specify separation character for getHeaderString
